measurement-kit/measurement-kit

src/common/pointer.hpp
src/protocols/dns.cpp
src/protocols/dns.hpp
test/protocols/dns.cpp

Spotted with valgrind while developing the socks5 feature. See d931724c0's comment for bug analysis and 71e12f6d5's comment for a description of the fix.

Fix dns use-after-free bug

---

src/common/libevent.h
src/net/buffer.hpp
src/net/connection.cpp
src/net/connection.h
src/net/connection.hpp
src/ooni/tcp_test.cpp
src/ooni/tcp_test.hpp
src/protocols/http.cpp
src/protocols/http.hpp
test/common/bufferevent.cpp
test/echo_client_evbuf.cpp
test/net/connection.cpp

This pull request increases the C++-ish-ness of connection. This is functional to next pull request, that will introduce socks5 and will make connection a class derived from a generic transport.

Make connection's API more C++-ish

---

src/net/connection.hpp
src/net/socks5.cpp
src/net/socks5.hpp
src/net/transport.cpp
src/net/transport.hpp
src/protocols/http.hpp
test/protocols/http.cpp

- Do not automatically use Tor's socks5
- Automatically use Tor instead when httpo://... URL are used

Refine SOCKS5 and Tor implementation

---

include/ight/common/check_connectivity.hpp
src/common/check_connectivity.cpp
test/protocols/dns.cpp

As @bassosimone suggested, a test based on github.com is not robust enough, since github.com could be blocked in some countries.

Make the connectivity check more robust using nexa.polito.it

---

README.md

This is not the best usage example ever, but it is a starting point. Tested that this compiles using clang++ (I have not checked whether it links but there's no reason why it should not).

Add minimal usage example

---

README.md

I've tried with 2 spaces but I really can't make it, and at the end of the day I'm more comfortable with 4 spaces indent.

[self bikeshedding] reindent with 4 spaces

---

include/ight/net/connection.hpp
src/net/connection.cpp

Diff contributed by Daniele Formichielli (Portolan), slightly tweaked by me.

Teach connection to use custom poller

---

include/measurement_kit/common.hpp
include/measurement_kit/common/delayed_call.hpp
include/measurement_kit/common/poller.hpp
include/measurement_kit/net/connection.hpp
include/measurement_kit/ooni/net_test.hpp
src/common/delayed_call.cpp
src/common/include.am
src/common/poller.cpp
src/ooni/net_test.cpp
test/common/bufferevent.cpp
test/common/poller.cpp

- separate Poller and DelayedCall
- remove SIGINT on UNIX hack
- model Poller::global() on Libs::global()
- coding style

Release engineering of poller

---

doc/common/constraints.md
doc/common/settings.md
doc/common/utils.md

With this and other pending pull requests, everything inside common should be documented.

Document more stuff inside common

---

doc/common/delayed_call.md
include/measurement_kit/common/delayed_call.hpp
include/measurement_kit/net/connection.hpp
include/measurement_kit/ooni/net_test.hpp
src/common/delayed_call.cpp
src/net/connection.cpp
src/ooni/net_test.cpp

This pull request should be merged after #156 because it is based on it. Since it is simple, I have labeled it as an hotfix.

Cleanup delayed call

---

include/measurement_kit/dns/query.hpp
include/measurement_kit/dns/resolver.hpp
include/measurement_kit/dns/response.hpp
include/measurement_kit/net/connection.hpp
src/dns/query.cpp
src/dns/query_impl.hpp
src/dns/resolver.cpp
src/dns/response.cpp
src/net/connection.cpp
src/ooni/dns_test.cpp
test/dns/query.cpp
test/dns/resolver.cpp
test/dns/response.cpp

- rename {r,R}equest as {q,Q}uery
- clang-format -i everything

Cleanup DNS class names and coding style

---

doc/dns/query.md
doc/dns/resolver.md
doc/dns/response.md
include/measurement_kit/dns/query.hpp
include/measurement_kit/dns/resolver.hpp
include/measurement_kit/dns/response.hpp
src/dns/query_impl.hpp

Super simple pull request moving dns documentation inside doc.

Move documentation below doc/dns

---

include/measurement_kit/net/transport.hpp

Define operator<< for transport

---

measurement_kit.podspec
mobile/ios/scripts/build_frameworks.sh

- make CocoaPod happy: provide dummy header
- add podspec file
Tested by me and @AntonioLangiu.

Enable CocoaPods

---

mobile/android/scripts/build_target.sh

Reduces x10 size of libmeasurement_kit.a

android: install -> install-strip

---

include/measurement_kit/traceroute/interface.hpp
src/traceroute/android.cpp

This pull request is based on issue #196.
Code is compiling and make check passes.
Closes #196.

send_probe send errorto error_cb_ and no more throws exceptions.

---

README.md
configure.ac
mobile/android/scripts/build_target.sh
mobile/ios/scripts/build_arch.sh

More consistent configure flags

---

include/measurement_kit/common/error.hpp
include/measurement_kit/traceroute.hpp
include/measurement_kit/traceroute/android.hpp
include/measurement_kit/traceroute/error.hpp
include/measurement_kit/traceroute/interface.hpp
src/traceroute/android.cpp
test/traceroute/android.cpp

Use common::Error rather than std::runtime_error.

---

configure.ac
doc/api/c++/report/entry.md
doc/api/c++/report/file_reporter.md
include/measurement_kit/common.hpp
include/measurement_kit/common/version.hpp
include/measurement_kit/ooni/dns_injection.hpp
include/measurement_kit/ooni/http_invalid_request_line.hpp
include/measurement_kit/ooni/net_test.hpp
include/measurement_kit/ooni/tcp_connect.hpp
include/measurement_kit/report.hpp
include/measurement_kit/report/base_reporter.hpp
include/measurement_kit/report/entry.hpp
include/measurement_kit/report/file_reporter.hpp
include/measurement_kit/report/report_entry.hpp
src/common/include.am
src/ooni/dns_injection.cpp
src/ooni/http_invalid_request_line.cpp
src/ooni/net_test.cpp
src/ooni/tcp_connect.cpp
src/report/base_reporter.cpp
src/report/file_reporter.cpp
src/report/include.am
test/report/file.cpp

Cleanup report API

---

doc/api/c++/net/buffer.md
include/measurement_kit/net/buffer.hpp
src/net/buffer.cpp
test/net/buffer.cpp

Buffer::readline returns Maybe<std::string>.

---

src/ext/include.am

Removed also yaml-cpp headers.
Closes #236

Removed Boost and yaml-cpp header

---

.gitignore
include/measurement_kit/net/transport.hpp
src/net/socks5.cpp
src/net/socks5.hpp
src/net/transport.cpp
test/include.am
test/net/transport.cpp

Allow to pass custom poller to net::connect()

---

doc/api/c++/common/libs.md
doc/private/c++/common/libs.md

Edited documentation.

---

doc/api/c++/net/transport.md
include/measurement_kit/net/transport.hpp
src/http/stream.hpp
src/net/emitter.hpp
src/net/transport.cpp
test/http/request.cpp
test/http/stream.cpp
test/net/transport.cpp

Simplify transport usage

---

README.md

Add Index to README.md

---

include/measurement_kit/ooni/dns_injection_test.hpp
include/measurement_kit/ooni/http_invalid_request_line_test.hpp
include/measurement_kit/ooni/tcp_connect_test.hpp

Teach ooni new API to get boolean value for set_verbose(); 
This closes #293

Teach tests to get boolean value for set_verbose

---

measurement_kit.podspec

Update the podspec file. Changes:
- Add all authors
- Improve version (and tag) control
- Remove branch specification because is not needed 
- Change prepare command, since now is possible to build from every folder
Thanks to @bassosimone for the given tips.

Update Podspec 

---

src/ooni/dns_injection.hpp
src/ooni/dns_test.hpp
src/ooni/http_invalid_request_line.hpp
src/ooni/http_test.hpp
src/ooni/include.am
src/ooni/ooni_test.cpp
src/ooni/ooni_test.hpp
src/ooni/tcp_test.hpp
test/ooni/net_test.cpp

Like in #323. I renamed and tested the changes. I think is ready to merge.

Rename net_test to ooni_test

---

include/measurement_kit/ooni/dns_injection_test.hpp
include/measurement_kit/ooni/http_invalid_request_line_test.hpp
include/measurement_kit/ooni/tcp_connect_test.hpp
src/ooni/dns_injection.cpp
src/ooni/http_invalid_request_line.cpp
src/ooni/ooni_test.cpp
src/ooni/ooni_test.hpp
src/ooni/tcp_connect.cpp
test/ooni/dns_injection_test.cpp
test/ooni/http_invalid_request_line_test.cpp
test/ooni/tcp_connect_test.cpp

Helps to implement the mobile application, especially Android. <strike>.**Before this is merged**, I'd like to **add a couple of regress tests** to make sure it does not break anything.</strike> [Now regress tests have been added!]

Allow to specify report file path

---

Makefile.am

To merge this pull request we need first to fix this issues:
* [test/common/delayed_call](https://github.com/measurement-kit/measurement-kit/issues/320)
* [test/net/connection](https://github.com/measurement-kit/measurement-kit/issues/191)

Run tests through Valgrind

---

include/measurement_kit/traceroute/android.hpp
src/traceroute/android.cpp

Custom logger added. Option 1 chosen.
Closes #297

traceroute: allow to use custom logger

---

doc/api/traceroute/android.md
doc/api/traceroute/error.md
doc/api/traceroute/interface.md

This pull request adds the documentation for traceroute.

Added traceroute documentation.

---

.gitignore
example/http/include.am
example/http/request.cpp
example/include.am
include/measurement_kit/http.hpp
src/http/client.cpp

Issue 355: increase abstraction of HTTP code

---

.gitignore
example/include.am
example/mlabns/include.am
example/mlabns/query.cpp
include/measurement_kit/mlabns.hpp
src/include.am
src/mlabns.cpp

Issue 333: implement basic mlabns client

---

doc/api/http.md
include/measurement_kit/http.hpp
test/http/funcs.cpp

This was discussed with @hellais when he was in Turin, but I
forgot to commit and push the diff.
Also, this is to get me going after a very long period in which I
did not commit anything and was veeeeery inactive.

http::GET() -> http::get()

---

example/dns/query.cpp
src/dns/query.cpp

<strike>This PR is an attempt to create a more abstract interface.  It is inspired by #362.
This pull request may not be complete. 
Do we need more examples? i.e. an example for each query()?
New function documentation is missing. Do we need to add it in this PR?</strike>
This PR adds an example usage of the new DNS API (as requested below) and, while there, it fixes a warning caused by not properly returning in case of error.

Add dns usage example and fix warning

---

src/net/bufferevent.hpp
src/net/connection.cpp
src/net/connection.hpp
src/net/transport.cpp
src/ooni/tcp_connect_impl.hpp
src/ooni/tcp_test_impl.hpp
test/net/transport.cpp
test/ooni/tcp_test.cpp

- use connect() interface to create transport where it is easy to do so
- change ooni/tcp-test to use public transport api rather than pulling in internal api

Start using new connect interface

---

include/measurement_kit/net/buffer.hpp
src/net/buffer.cpp
test/net/buffer.cpp

Yeah yeah yeah more syntactic sugar!

buffer: add more constructors

---

.gitignore
src/net/connection.cpp
src/net/connection.hpp
src/net/emitter.cpp
src/net/emitter.hpp
src/net/socks5.cpp
src/net/socks5.hpp

(While there, also add `.vagrant` to .gitignore.)

net: slightly refactor code

---

.gitignore
example/net/listen.cpp
include/measurement_kit/net/error.hpp
src/net/listen.cpp
src/net/listen.hpp

Based on libevent's listener, this simple and private listener is what I need to write more examples and tests.

Add private very simple listener

---

.gitignore
example/net/transport.cpp
src/net/socks5.cpp
src/net/socks5.hpp
src/net/transport.cpp
test/net/socks5.cpp

See commit message for more details.

socks5: attach to already established connection

---

.travis.yml

Set the correct image to build measurement-kit for iOS on travis!

Set the correct osx-image to build measurement-kit for iOS on travis

---

example/net/connect.cpp

- use public API
- add option to use tor socks

enhance example/net/connect

---

.clang-format
src/http/response_parser.cpp
src/http/response_parser.hpp
test/http/response_parser.cpp

This pull request, in particular, adds a new http parser. I tried to gently evolve the existing parser in the desired direction, but after I while I realized a rewrite was better.
Of course, this is *not* a rewrite from scratch, but rather refactoring.

http: add rewritten http parser

---

test/net/connection.cpp

Convert tests in test/net/connection.cpp to use the connect() factory
that receives a callback as argument. This is required to prepare
for removal of the connect() factory that returns ErrorOr<Transport>.

t/n/connection: use net::connect(..., cb)

---

include/measurement_kit/dns/dns.hpp
src/dns/query.hpp
test/dns/query.cpp

Add dns tests

---

src/net/connection.cpp
test/dns/query.cpp

While there also repair a failing DNS test which prevented the build to terminate.

connection: clear state inside close()

---

include/measurement_kit/common/var.hpp
test/common/var.cpp

Add static_pointer_cast to Var

---

acinclude.m4
build/dependency
build/patch/libressl/0001-build-just-needed-subdir.patch
build/spec/libevent

I moved the commit related to build/dependency in this branch.
The explanation of the changes are in the commit messages.
Please check this branch locally before merging, because it can't be tested with travis, we are not building the dependencies

Build dependency script improvements

---

src/common/async.cpp
src/common/poller.cpp

Move the evthread initialization to the poller

---

src/ooni/tcp_connect_impl.hpp

Bug spotted by @AntonioLangiu, thanks!

ooni/tcp_connect_impl.hpp: fix constructor invocation

---

doc/api/dns.md
doc/api/http/http.md
example/http/request.cpp
example/net/connect.cpp
example/net/transport.cpp
include/measurement_kit/http/http.hpp
include/measurement_kit/ooni/dns_injection_test.hpp
src/dns/query.hpp
src/http/request.hpp
src/http/request_serializer.hpp
src/mlabns/mlabns.cpp
src/net/connect.cpp
src/net/connect.hpp
src/net/socks5.cpp
src/net/transport.cpp
src/ooni/dns_injection_impl.hpp
src/ooni/dns_test_impl.hpp
test/dns/query.cpp
test/http/client.cpp
test/http/request.cpp
test/http/request_serializer.cpp
test/net/connect.cpp
test/net/socks5.cpp
test/net/transport.cpp
test/ooni/dns_injection.cpp
test/ooni/tcp_connect.cpp

See issue #522. 
To finish this PR I need to change the tag in the documentation.

Use unique tags as key in the settings dictionary

---

build/ios/scripts/build.sh
build/ios/scripts/build_arch.sh

As in the description. This is the refactor of #514

Improvents for iOS build script

---

include/measurement_kit/net/buffer.hpp
include/measurement_kit/net/error.hpp
src/net/buffer.cpp

1) add factory to construct a Var<Buffer>
2) add code to read uint8, uint16, and uint32

Two net/buffer enhancements

---

include/measurement_kit/common/logger.hpp
src/common/logger.cpp

While there remove documentation stating the obvious

logger: make logv thread safe

---

src/common/poller.hpp

Another diff functional to future templatization of this class. To implement
the template, we need to set the destructor function in the constructor since
we cannot templatize the whole class, because it is a derived class.
After this change, I think the next diff is probably going to be the real
templatization of the class with annexed cleanup of libs.hpp.

poller: use Var<> to decide deletor in constructor

---

src/ooni/http_invalid_request_line_impl.hpp
test/ooni/http_invalid_request_line.cpp
test/ooni/http_invalid_request_line_test.cpp

Teach http_invalid_request line to pass the options

---

.travis.yml

.travis.yml: fix coverage

---

.gitignore
include/measurement_kit/common.hpp
include/measurement_kit/common/continuation.hpp
include/measurement_kit/common/reactor.hpp
test/common/continuation.cpp

Perhaps not super intuitive, the continuation is anyway useful
for implementing simple coroutines. Required in NDT code.

Add continuation template

---

include/measurement_kit/common/settings.hpp
include/measurement_kit/net/error.hpp
src/net/ssl-context.cpp
test/net/transport.cpp

1) be more verbose about the issue that certificate bundle is missing
2) throw a specific exception in that case
3) while here, Settings::global() should return a Var<Settings>

Quick fix for mlabns problem

---

.gitignore
Makefile.am
build/valgrind/openssl.supp
test/mlabns/mlabns.cpp

In this unit-tests I assume that the ca-bundle has been found.

Add mlabns unit test

---

.travis.yml

While there, move comment near the statements it documents.
When merged, this would be commit number 1492. With this, we exit middle ages :-D :-D :-D.

.travis.yml: silence run-valgrind

---

.gitignore
example/net/discard.cpp

A discard server is always useful when developing other stuff.

Add net/discard example

---

include/measurement_kit/common/error.hpp
src/common/runner.cpp

This ports changes in #543 to the current implementation of Runner.

Runner: make sure thread is running before continuing

---

measurement_kit.podspec

Use the correct min-ios version

---

test/common/error_or.cpp
test/dns/query.cpp
test/net/transport.cpp
test/ooni/tcp_test.cpp

As in the description. The warnings are explained in the commit text.

Fix warnings while building the tests

---

src/ooni/dns_injection_impl.hpp
src/ooni/ooni_test_impl.hpp
src/ooni/tcp_connect_impl.hpp

Please see the issue #338 
This closes #338!

Avoid duplicating code in dns_injection_impl and tcp_connect_impl

---

src/mlabns/mlabns.cpp
src/mlabns/mlabns.hpp
src/mlabns/mlabns_impl.hpp
test/mlabns/mlabns.cpp

I added the tests listed in #465 
I applyed clang-format as last commit.
This closes #465 and #399.

Add some mlabns tests

---

include/measurement_kit/common/net_test_dsl.hpp

net_test_dsl.hpp: allow settings of any type

---

include/measurement_kit/common.hpp
include/measurement_kit/common/utils.hpp
src/common/utils.hpp

Should help @lorenzoPrimi with the Apps.

Export time-related utils functions

---

.gitignore
example/dns/query.cpp
example/net/connect.cpp
src/net/connect.cpp

Make sure the timeout is correctly passed to connect_logic().
While there, also fix other inconsistencies.
Bugs spotted by @hellais.

Fix net/connect timeout

---

autogen.sh

Increase it MANY times. Now it's blazingly fast! Inspired by how
CodoaPods downloads repositories from github.

autogen.sh: increase speed of fetching git repos

---

configure.ac
doc/api/common/version.md
doc/index.md
example/ndt/ndt.cpp
include/measurement_kit/common/version.hpp
include/measurement_kit/ndt/ndt_test.hpp
include/measurement_kit/ndt/run.hpp
include/measurement_kit/ooni/collector_client.hpp
include/measurement_kit/report/entry.hpp
measurement_kit.podspec
src/ndt/internal.hpp
src/ndt/messages.cpp
src/ndt/ndt_test.cpp
src/ndt/protocol_impl.hpp
src/ndt/run.cpp
src/ndt/run_impl.hpp
src/ndt/test_c2s_impl.hpp
src/ndt/test_s2c.cpp
src/ndt/test_s2c_impl.hpp
src/report/entry.cpp
test/ndt/run.cpp
test/ndt/test_s2c.cpp

This has been running on a experimental app for quite some time now. The diff is simple enough that I think this can qualify as hotfix.
Since this changes a public header, it leads us to `v0.3.0`-land.

ndt as ooni test

---

include/measurement_kit/common/logger.hpp
src/common/logger.cpp
src/ndt/internal.hpp
src/ndt/test_c2s_impl.hpp
src/ndt/test_s2c_impl.hpp

Apps would intercept JSON encoded messages and would deal with them.

ndt: pass json-encoded speed snapshots to logger

---

include/measurement_kit/ooni/collector_client.hpp
src/ooni/collector_client_impl.hpp

Must have this in to release v0.2.6.
Closes #717.

Use OONI's default collector

---

ChangeLog.md
include/measurement_kit/ooni/collector_client.hpp
src/ooni/collector_client_impl.hpp

This pull request merges stable into master to make sure the two branches do not diverge too much during the development process.

Merge stable into master

---

src/ndt/run_impl.hpp

ndt: save server address and port

---

.gitignore
include/measurement_kit/http/http.hpp
src/ooni/templates.cpp
test/http/headers.cpp

http: headers search now case insensitive

---

include/measurement_kit/common/logger.hpp
src/common/logger.cpp

Breakage initially reported by @AntonioLangiu.

logger: fix build with GCC 4.9

---

src/ooni/ooni_test.cpp
test/ooni/ooni_test.cpp

Add settings required by NetProbe

---

ChangeLog.md
configure.ac
doc/api/common/version.md
doc/index.md
include/measurement_kit/common/version.hpp
measurement_kit.podspec

Such that we can start building packages and testing the new
web-connectivity test and other goodies in the Apps.

Tag v0.3.0-alpha

---

src/libmeasurement_kit/ooni/ooni_test.cpp

This pull request addresses #777

ooni_test.cpp: allow caller to set probe_{ip,asn,cc}

---

ChangeLog.md
build/android/library
build/ios/library
configure.ac
doc/api/common/version.md
doc/index.md
include/measurement_kit/common/delegate.hpp
include/measurement_kit/common/logger.hpp
include/measurement_kit/common/reactor.hpp
include/measurement_kit/common/version.hpp
include/measurement_kit/dns/dns.hpp
include/measurement_kit/net/transport.hpp
include/measurement_kit/ooni/collector_client.hpp
include/measurement_kit/ooni/dns_injection.hpp
include/measurement_kit/ooni/http_invalid_request_line.hpp
include/measurement_kit/ooni/ooni_test.hpp
include/measurement_kit/ooni/tcp_connect.hpp
include/measurement_kit/ooni/web_connectivity.hpp
measurement_kit.podspec
src/libmeasurement_kit/net/transport.cpp
src/libmeasurement_kit/ooni/collector_client.cpp
src/libmeasurement_kit/ooni/ooni_test.cpp

Like #854 but using the correct base branch!

Tag v0.3.2 (second attempt)

---

include/measurement_kit/cmdline/cmdline.hpp

cmdline.hpp: Use macros to simplify code

---

src/libmeasurement_kit/ooni/ooni_test.cpp

Bug spotted and reported by @lorenzoPrimi, thank you!

Make no_collector/no_file_report really usable

---

include/measurement_kit/dns/dns.hpp
src/libmeasurement_kit/dns/query.cpp
src/libmeasurement_kit/dns/query_impl.hpp
src/libmeasurement_kit/ooni/utils_impl.hpp
test/dns/query.cpp

dns: pass logger to query()

---

include/measurement_kit/dns/dns.hpp
include/measurement_kit/ooni/templates.hpp
src/libmeasurement_kit/cmdline/dns_query.cpp
src/libmeasurement_kit/dns/query.cpp
src/libmeasurement_kit/dns/query_impl.hpp
src/libmeasurement_kit/net/connect.cpp
src/libmeasurement_kit/ooni/dns_injection.cpp
src/libmeasurement_kit/ooni/templates.cpp
src/libmeasurement_kit/ooni/utils_impl.hpp
src/libmeasurement_kit/ooni/web_connectivity.cpp
test/dns/query.cpp
test/ooni/templates.cpp

dns.hpp: pass a Var<Message> to the callback

---

src/libmeasurement_kit/ooni/web_connectivity.cpp

After #889, I tested again on the device only to notice that the
test still does not work because the ssl-bundle option is not correctly
passed to the caller. Thus, prepare a better fix by which we leverage
that options we receive are copied and we only override the settings
we need to override, and the rest is unchanged.

web_connectivity: use copied caller options for control

---

include/measurement_kit/net/connect.hpp
src/libmeasurement_kit/net/connect.cpp
src/libmeasurement_kit/net/connect.hpp
src/libmeasurement_kit/net/connect_impl.hpp
test/net/connect.cpp

This diff has been extracted from #710 to ease review.
The plan is to merge this into master and then merge master in #710.

net: measure connect time during connect

---

src/libmeasurement_kit/dns/query_impl.hpp

* To pass the Logger to the callback called by libevent
a solution that I found was to put the logger inside
the context structure we pass to evdns_resolver_*
* robustness fix
Backports: #912 (backported by @bassosimone)
Conflicts:
- src/libmeasurement_kit/dns/query_impl.hpp

Log dns debug to the correct logger

---

include/measurement_kit/ooni/collector_client.hpp
src/measurement_kit/cmdline/oonireport.cpp

collector_client.hpp: remove backward compat stuff

---

doc/api/common/version.md
include/measurement_kit/common.hpp
include/measurement_kit/common/version.h
src/libmeasurement_kit/common/version.cpp
test/common/version.cpp

version: use C linkage function

---

include/measurement_kit/net/connect.hpp
src/libmeasurement_kit/http/request_impl.hpp
src/libmeasurement_kit/ndt/internal.hpp
src/libmeasurement_kit/ndt/protocol_impl.hpp
src/libmeasurement_kit/ndt/test_c2s.cpp
src/libmeasurement_kit/ndt/test_c2s_impl.hpp
src/libmeasurement_kit/ndt/test_s2c.cpp
src/libmeasurement_kit/ndt/test_s2c_impl.hpp
src/libmeasurement_kit/net/connect.cpp
src/libmeasurement_kit/net/connect.hpp
src/libmeasurement_kit/net/connect_impl.hpp
src/libmeasurement_kit/ooni/templates.cpp
test/http/request.cpp
test/ndt/protocol.cpp
test/ndt/test_c2s.cpp
test/ndt/test_s2c.cpp
test/net/connect.cpp

Reactor should come before logger in function args

---

include/measurement_kit/common/aaa_base.hpp
include/measurement_kit/portable/netinet/tcp.h
src/libmeasurement_kit/libevent/listen.hpp
src/libmeasurement_kit/net/connect.cpp
src/libmeasurement_kit/net/utils.cpp
src/libmeasurement_kit/net/utils.hpp

Always disable the Nagle algorithm

---

CMakeLists.txt
test/nettests/http_invalid_request_line.cpp
test/nettests/tcp_connect.cpp
test/report/report.cpp

Not production ready yet but more useful than before.
Tested with macOS (where you need to specify some command line flags) and VoidLinux.

Improve cmake for Unix

---

build/android/dependency
build/android/make-toolchain
build/ios/cross
build/ios/library
build/patch/post-autogen/libressl/0002-add-getentropy-decl.c
build/spec/Catch
build/spec/all
build/spec/json
build/spec/libressl
build/spec/strtonum
build/spec/tls_verify
include/measurement_kit/ext/json.hpp
src/libmeasurement_kit/ext/catch.hpp

Update dependencies for v0.4.0

---

CMakeLists.txt

- fail if we cannot find required dependencies
- include headers to source files (should fix bug reported
recently by @hellais)

Improve the CMakeLists.txt file

---

src/libmeasurement_kit/nettests/multi_ndt.cpp
src/measurement_kit/cmdline/multi_ndt.cpp

- provide shortcuts for interesting bits of info in advanced
- better key name ("key" -> "fastest_test")
Bump test version.

Improve multi_ndt entry format

---

doc/api/nettests/base_test.md
include/measurement_kit/nettests/runnable.hpp
src/libmeasurement_kit/nettests/runnable.cpp
src/measurement_kit/cmdline/web_connectivity.cpp

runnable: implement max_runtime option

---

doc/api/dns.md
doc/api/net/connect.md
include/measurement_kit/dns/dns.hpp
include/measurement_kit/net/connect.hpp
src/libmeasurement_kit/dns/query.cpp
src/libmeasurement_kit/net/connect.cpp
src/libmeasurement_kit/net/connect.hpp
test/dns/query.cpp
test/net/connect.cpp

As described in the issue #988

Move dns resolution function from net to dns

---

build/ios/library
build/patch/pre-autogen/libevent/common/000.patch

Fix libevent clock gettime

---

doc/api/nettests/base_test.md
include/measurement_kit/nettests/runnable.hpp
src/libmeasurement_kit/nettests/runnable.cpp
test/nettests/runnable.cpp

nettests: randomize input

---

ChangeLog.md
build/android/cross
build/android/dependency
build/android/make-toolchain
doc/api/nettests/base_test.md
include/measurement_kit/nettests/runnable.hpp
src/libmeasurement_kit/dns/system_resolver_impl.hpp
src/libmeasurement_kit/ndt/messages_impl.hpp
src/libmeasurement_kit/nettests/runnable.cpp
test/nettests/runnable.cpp

This merges changes in v0.4.0-alpha.3 into master.

Merge stable

---

.travis.yml
build/docker/script/run
build/docker/script/setup
build/docker/spec/coveralls
build/travis

This pull request forward ports to master #1066 that has already been applied to stable.

Forward port patch #1066 to master

---

build/dependency
build/spec/Catch
build/spec/citrus
build/spec/geoip
build/spec/http-parser
build/spec/json
build/spec/libevent
build/spec/libressl
build/spec/mk_builtin_ca_bundle
build/spec/strtonum
build/spec/tls_verify

Closes #869.
Backported from #1017.

build/dependency: implement quick git clone

---

build/dependency

Should be an hotfix. For robustness, I'm also checking whether cross compiling libressl still works okay.

build/dependency: factor more operations

---

README.md

Backport of #1072 to `stable`.

README.md: attempt to fix coveralls badge

---

build/ios/build-frameworks
doc/api/net.md
doc/api/net/utils.md
include/measurement_kit/net.hpp
include/measurement_kit/net/utils.hpp
src/libmeasurement_kit/net/utils.cpp
src/libmeasurement_kit/ooni/templates.cpp
src/libmeasurement_kit/ooni/utils.cpp
src/libmeasurement_kit/ooni/utils.hpp
src/libmeasurement_kit/ooni/web_connectivity.cpp
test/net/utils.cpp
test/ooni/utils.cpp

Fixes issues observed when running web-connectivity on devices.
Should probably be tested again on devices before blessing the next release of measurement-kit.

net: improve handling of address:port

---

.gitignore
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/report/report.cpp
test/report/report.cpp

report: Allow to specify application name and version

---

build/ios/cross

1. move log statement down
2. host triplet: s/darwin14/darwin/
3. min ios version: 8.0
Hotfix extracted from #1017

Tweak build/ios/cross

---

src/libmeasurement_kit/report/report.cpp

Also, as in ooni-probe, allow to override it.
Before merging, testing required on:

report: include the platform

---

.gitignore
src/libmeasurement_kit/ndt/internal.hpp
src/libmeasurement_kit/ndt/run_impl.hpp
src/libmeasurement_kit/ndt/test_c2s.cpp
src/libmeasurement_kit/ndt/test_c2s_impl.hpp
src/libmeasurement_kit/ndt/utils.cpp
src/libmeasurement_kit/ndt/utils.hpp
src/libmeasurement_kit/nettests/multi_ndt.cpp
src/libmeasurement_kit/nettests/ndt.cpp
src/measurement_kit/cmdline/multi_ndt.cpp
test/ndt/test_c2s.cpp

Add support for reporting simple and advanced stats inside of the ndt test.

Feature: NDT stats

---

src/libmeasurement_kit/ooni/web_connectivity.cpp
src/measurement_kit/cmdline/http_request.cpp
test/http/request.cpp

xref: TheTorProject/ooni-probe#729

Port test case from TheTorProject/ooni-probe#729

---

test/http/request.cpp
test/ooni/bouncer.cpp

Includes feedback from @hellais

Repair regress tests

---

build/android/cross

@anadahz  says:
> Make @bassosimone happy.
And that's true! Thanks!!!

Remove bashism

---

test/http/request.cpp

See https://travis-ci.org/measurement-kit/measurement-kit/builds/209257407

Repair regress tests after travis failure

---

doc/api/http/request.md
src/libmeasurement_kit/ooni/templates.cpp

ooni/template.cpp: don't assume !!response->request

---

.travis.yml
build/ci/travis

In other words, finish dealing with the fact that now we build
not only pushes but also pull requests.

Finish fixing travis branch handling

---

src/libmeasurement_kit/http/request.cpp
test/http/request.cpp

As noted during #1174, it's odd that we return NoError() when
there is EOF and we've not determined whether body could be
terminated by EOF. That is actually a protocol violation more
than a case that we should treat as success.
Add test cases for both body terminated by EOF and EOF received
before anything else, so we're robust to future changes.

http: treat EOF-instead-of-response as error

---

doc/api/common/mock.md
include/measurement_kit/common/mock.hpp
src/libmeasurement_kit/common/utils_impl.hpp
src/libmeasurement_kit/http/request_impl.hpp
src/libmeasurement_kit/mlabns/mlabns_impl.hpp
src/libmeasurement_kit/ndt/messages_impl.hpp
src/libmeasurement_kit/ndt/protocol_impl.hpp
src/libmeasurement_kit/ndt/run_impl.hpp
src/libmeasurement_kit/ndt/test_c2s_impl.hpp
src/libmeasurement_kit/ndt/test_meta_impl.hpp
src/libmeasurement_kit/ndt/test_s2c_impl.hpp
src/libmeasurement_kit/net/connect_impl.hpp
src/libmeasurement_kit/ooni/bouncer_impl.hpp
src/libmeasurement_kit/ooni/collector_client_impl.hpp
src/libmeasurement_kit/ooni/resources_impl.hpp
src/libmeasurement_kit/ooni/utils_impl.hpp

@joelanders, do you think that this diff increases readability/understandability?

mock.hpp: reduce implicit MK_MOCK_NAMESPACE magic

---

configure.ac
doc/api/common/version.md
doc/index.md
include/measurement_kit/common/version.h
measurement_kit.podspec

We're now hacking v0.6.0-dev

---

build/valgrind/openssl.supp
doc/api/common/reactor.md
include/measurement_kit/common/ptr_.hpp
include/measurement_kit/common/reactor.hpp
src/libmeasurement_kit/libevent/poller.cpp
src/libmeasurement_kit/libevent/poller.hpp
src/libmeasurement_kit/libevent/poller_impl.hpp
test/libevent/poller.cpp

Required to implement a "remote" reactor in a background thread.

reactor: implement "autostop" feature

---

.gitignore
doc/api/common/reactor.md
include/measurement_kit/common/reactor.hpp
test/common/reactor.cpp

This code is similar to, but more general than, the code we
currently use in Runner::run_test().

reactor: add algorithms for running tasks

---

doc/api/nettests/runner.md
include/measurement_kit/nettests/runner.hpp
src/libmeasurement_kit/nettests/runner.cpp

This is much simpler than #1243 but should pretty much provide
us with the same functionality (in a less cool way).

runner: allow to run arbitrary tasks

---

.clang-format
.gitignore
doc/api/common.md
doc/api/common/json.md
doc/api/common/maybe.md
doc/api/common/sandbox.md
include/measurement_kit/common/json.hpp
include/measurement_kit/common/maybe.hpp
include/measurement_kit/common/sandbox.hpp
test/common/json.cpp
test/common/maybe.cpp
test/common/sandbox.cpp

Instrumental to other work that I'll commit later (big diffs give me headache).

Improve our json processing capabilities

---

acinclude.m4
build/docker/spec/coveralls
doc/api/nettests/base_test.md
include/measurement_kit/nettests/nettests.hpp
include/private/nettests/runnable.hpp
include/private/nettests/utils.hpp
include/private/nettests/utils_impl.hpp
src/libmeasurement_kit/nettests/base_test.cpp
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/nettests/utils.cpp
src/measurement_kit/cmd/web_connectivity.cpp
test/http/request.cpp
test/nettests/utils.cpp

Supersedes #1132.
Closes #308.

Allow to pass nettests input from command line

---

acinclude.m4
build/android/make-toolchain
build/docker/spec/coveralls
build/ios/library
build/spec/Catch
build/spec/geoip
include/private/ext/catch.hpp
include/private/net/emitter.hpp
include/private/nettests/utils_impl.hpp
src/libmeasurement_kit/ndt/messages.cpp
test/http/request.cpp

Simple patches that it's safe to cherry-pick immediately into master from #1271.

Cherry picks from v0.7.0-beta branch

---

build/ios/archive-library
build/ios/library
build/spec/mk
configure.ac
doc/api/common/version.md
doc/index.md
include/measurement_kit/common/version.h
measurement_kit.podspec

I accidentally forgot to commit this, damn!

Bump version to v0.8.0-dev

---

include/private/ooni/utils.hpp
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/ooni/utils.cpp
src/libmeasurement_kit/ooni/web_connectivity.cpp
test/ooni/utils.cpp

fix(geoip): make cache thread local

---

include/private/ooni/utils.hpp
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/ooni/utils.cpp
src/libmeasurement_kit/ooni/web_connectivity.cpp
test/ooni/utils.cpp

This reverts commit b4ad18ce684c85de93799c39ebbb971f47744fcd.

Revert "fix(geoip): make cache thread local (#1314)"

---

include/measurement_kit/http/http.hpp
include/private/dns/getaddrinfo_async.hpp
include/private/http/response_parser.hpp
include/private/net/libssl.hpp
include/private/neubot/dash_impl.hpp
include/private/ooni/bouncer_impl.hpp
include/private/ooni/collector_client_impl.hpp
src/libmeasurement_kit/common/utils.cpp
src/libmeasurement_kit/http/request.cpp
src/libmeasurement_kit/net/connect.cpp
src/libmeasurement_kit/ooni/web_connectivity.cpp
test/http/request.cpp

Fixes implemented while debugging why dash does not work on some mobile networks.

Make logging more clear and less redundant

---

include/measurement_kit/http/http.hpp
include/private/neubot/dash_impl.hpp
src/libmeasurement_kit/http/request.cpp
test/http/request.cpp

feature(http): implement `ignore_body' setting

---

include/private/http/response_parser.hpp
test/http/response_parser.cpp

fix(response_parser): stop parsing after first message 

---

example/http/request.cpp
include/measurement_kit/ooni/templates.hpp
include/private/http/response_parser.hpp
test/http/response_parser.cpp
test/ooni/web_connectivity.cpp

While there, add regress tests.
Closes #1312.

fix(upgrade): correctly deal with upgrade

---

src/measurement_kit/cmd/dash.cpp
src/measurement_kit/cmd/multi_ndt.cpp
src/measurement_kit/cmd/ndt.cpp
src/measurement_kit/utils.cpp

fix(cli): flush stdout more consistently

---

doc/tutorial/ios.md
example/nettests/multithread.cpp
example/nettests/simple.cpp
include/measurement_kit/nettests/nettests.hpp
src/libmeasurement_kit/nettests/base_test.cpp
src/measurement_kit/cmd/dash.cpp
src/measurement_kit/cmd/dns_injection.cpp
src/measurement_kit/cmd/http_header_field_manipulation.cpp
src/measurement_kit/cmd/http_invalid_request_line.cpp
src/measurement_kit/cmd/meek_fronted_requests.cpp
src/measurement_kit/cmd/multi_ndt.cpp
src/measurement_kit/cmd/ndt.cpp
src/measurement_kit/cmd/web_connectivity.cpp
src/measurement_kit/main.cpp
src/measurement_kit/utils.cpp
test/nettests/dns_injection.cpp
test/nettests/http_invalid_request_line.cpp
test/nettests/tcp_connect.cpp
test/nettests/utils.hpp
test/nettests/web_connectivity.cpp

nettests: start deprecating some APIs 

---

include/measurement_kit/nettests/nettests.hpp
include/private/nettests/runnable.hpp
src/libmeasurement_kit/nettests/base_test.cpp
src/libmeasurement_kit/nettests/runnable.cpp
src/measurement_kit/main.cpp

feature(nettests): allow arbitrary annotations

---

include/measurement_kit/ooni/utils.hpp
src/libmeasurement_kit/ooni/utils.cpp
test/ooni/utils.cpp

Requested by @lorenzoPrimi in #1407.
Closes #1407.

feature: implement find_location as a free function

---

include/measurement_kit/common/data_usage.hpp
include/measurement_kit/common/portable/arpa/nameser.h
include/measurement_kit/common/reactor.hpp
include/measurement_kit/nettests/nettests.hpp
include/private/common/libevent_reactor.hpp
include/private/dns/getaddrinfo_async.hpp
include/private/dns/utils.hpp
include/private/libevent/dns.hpp
include/private/net/emitter.hpp
include/private/nettests/runnable.hpp
src/libmeasurement_kit/nettests/base_test.cpp
src/libmeasurement_kit/nettests/runnable.cpp
src/measurement_kit/main.cpp
src/measurement_kit/utils.cpp

Measure data usage

---

src/libmeasurement_kit/nettests/base_test.cpp

base_test: break circular ref, fix node bindings

---

include/private/neubot/dash_impl.hpp

This is so hotfixish that we can for sure include it in v0.8.0.

fix(dash): enforce random UUID

---

src/libmeasurement_kit/nettests/facebook_messenger.cpp
src/libmeasurement_kit/nettests/telegram.cpp
src/libmeasurement_kit/nettests/whatsapp.cpp
src/libmeasurement_kit/ooni/facebook_messenger.cpp
src/libmeasurement_kit/ooni/telegram.cpp
src/libmeasurement_kit/ooni/whatsapp.cpp

https://github.com/measurement-kit/measurement-kit/issues/1492
This fixes all remaining bugs.

IM test logic fixing

---

src/libmeasurement_kit/nettests/facebook_messenger.cpp
src/libmeasurement_kit/nettests/telegram.cpp
src/libmeasurement_kit/nettests/whatsapp.cpp
src/libmeasurement_kit/ooni/facebook_messenger.cpp
src/libmeasurement_kit/ooni/telegram.cpp
src/libmeasurement_kit/ooni/whatsapp.cpp

* bug from typo
* remove suboptimalities
* wipe bugs around
* declare helper function static
* new features, bug fixes, and optimizations
* logic
* report endpoint http blocking in telegram
* ErrorOr<bool> -> bool
* more reachability/consistency logic
* [ci skip] bump patch version
* [ci skip] bump patch version
* bump

Backport #1498: IM test logic fixing

---

build/docker/coveralls
build/docker/spec/valgrind-clang
build/docker/valgrind-clang
build/docker/valgrind-gcc
doc/tutorial/unix.md

- artful for valgrind, where valgrind seems to work okay (no weird issues like in zesty, but correctly like it used to work on yakkety)
- zesty for coveralls, because cpp-coveralls doesn't seem to work on artful

fix(build): yakkety is no more, find replacements

---

include/measurement_kit/common/data_usage.hpp
include/measurement_kit/nettests/nettests.hpp
src/libmeasurement_kit/nettests/base_test.cpp

I am going to merge this as soon as the PR completes, since this diff has been approved by @lorenzoPrimi.

Start refactoring API after #1555

---

ChangeLog.md
Doxyfile
autogen.sh
build/ios/archive-library
build/ios/dependency
build/ios/library
build/spec/mk
configure.ac
doc/api/common/version.md
doc/index.md
include/measurement_kit/common/version.h.in
measurement_kit.podspec
src/libmeasurement_kit/http/request.cpp
src/libmeasurement_kit/ooni/templates_impl.hpp
test/http/request.cpp
test/http/response_parser.cpp
test/ooni/templates.cpp

Integration branch for MK v0.8.3. Things to do:

Release v0.8.3

---

build/ios/cross

Signed-off-by: Simone Basso <bassosimone@gmail.com>

build/cross/ios: disable thread local for i386

---

src/libmeasurement_kit/nettests/web_connectivity.cpp

fix(web_connectivity): pass the original URL to the app

---

include/measurement_kit/README.md
script/autoapi/autoapi
src/libmeasurement_kit/engine.cpp

autoapi: expose all settings needed by OONI mobile

---

include/measurement_kit/README.md
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/nettests/runnable.hpp
test/nettests/runnable.cpp

Closes #1638 
Doing this now because I already had an half-working branch. And, then, I could choose to keep yet another half working branch or do the effort to merge it into master.

runnable: remove now-unused callbacks

---

Doxyfile
configure.ac
include/measurement_kit/common/version.h
include/measurement_kit/common/version.h.in
script/update-includes
src/libmeasurement_kit/nettests/runnable.cpp
test/dns/system_resolver.cpp
test/http/request.cpp

Release 0.9.4

---

Doxyfile
configure.ac
include/measurement_kit/common/version.h
include/measurement_kit/common/version.h.in
script/update-includes
src/libmeasurement_kit/nettests/runnable.cpp

Backports #1759 to the stable branch.

Release 0.9.5

---

include/measurement_kit/internal/collector/collector.h
include/measurement_kit/internal/vendor/http_parser.h
include/measurement_kit/internal/vendor/json.hpp
include/measurement_kit/internal/vendor/mkcollector.hpp
include/private/catch.hpp
script/vendor/catch
script/vendor/http_parser
script/vendor/json
script/vendor/mkcollector
src/libmeasurement_kit/collector/collector.cpp
src/libmeasurement_kit/vendor/http_parser.c

Each dependency is in its own commit where I explain why I'm upgrading.
Closes #1792

Upgrade all vendored dependencies for v0.10.2

---

.ci/travis/AUTHORS
.ci/travis/LICENSE
.ci/travis/README.md
.ci/travis/alpine/Dockerfile
.ci/travis/debian/Dockerfile
.ci/travis/script/autotools
.ci/travis/script/cmake
.ci/travis/script/docker-run
.ci/travis/script/travis
.gitmodules
.travis.yml

.ci/common (subrepo) => .ci/travis (vendored)

---

Doxyfile
configure.ac
include/measurement_kit/README.md
include/measurement_kit/common/version.h
include/measurement_kit/common/version.h.in
include/measurement_kit/internal/vendor/mkcollector.hpp
include/measurement_kit/internal/vendor/mkcurl.hpp
include/private/catch.hpp
script/autoapi/autoapi
script/update-includes
script/vendor/catch
script/vendor/mkcollector
script/vendor/mkcurl
src/libmeasurement_kit/engine/autoapi.cpp
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/ooni/http_invalid_request_line.cpp
src/libmeasurement_kit/ooni/templates_impl.hpp
src/libmeasurement_kit/ooni/utils.cpp
src/libmeasurement_kit/ooni/utils.hpp
src/measurement_kit/cmd/dash.cpp
src/measurement_kit/cmd/dns_injection.cpp
src/measurement_kit/cmd/ndt.cpp
src/measurement_kit/cmd/tcp_connect.cpp
src/measurement_kit/cmd/web_connectivity.cpp
src/measurement_kit/cmd/whatsapp.cpp
src/measurement_kit/cmdline.hpp
src/measurement_kit/main.cpp
src/measurement_kit/utils.cpp

This PR contains some commits that are meant to be included in v0.10.4.

Release v0.10.4

---

.ci/travis/script/autotools
.ci/travis/script/docker-run
configure.ac
include/measurement_kit/README.md
script/autoapi/autoapi
src/libmeasurement_kit/common/fmap.hpp
src/libmeasurement_kit/common/utils.hpp
src/libmeasurement_kit/engine/autoapi.cpp
src/libmeasurement_kit/nettests/dash.cpp
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/neubot/dash_impl.hpp
src/libmeasurement_kit/ooni/orchestrate.cpp
src/libmeasurement_kit/ooni/utils_impl.hpp
src/libmeasurement_kit/ooni/web_connectivity.cpp
src/measurement_kit/main.cpp
test/dns/query.cpp
test/dns/system_resolver.cpp
test/ooni/orchestrate.cpp
test/ooni/templates.cpp

This PR addresses many outstanding open issues for MK v0.10.5: https://github.com/measurement-kit/measurement-kit/milestone/20.
You should review every commit independently and refer to the related issue.

More work towards MK v0.10.5

---

include/measurement_kit/README.md
src/libmeasurement_kit/mlabns/mlabns_impl.hpp
test/dns/query.cpp
test/dns/system_resolver.cpp

mlabns: use the new locate service

---

Doxyfile
configure.ac
include/measurement_kit/common/version.h
include/measurement_kit/common/version.h.in
script/autogen.d/geoip
script/update-includes

* fix the build by fetching MaxMind databases from our mirror
* bump the version number

Release v0.10.9

---

Doxyfile
configure.ac
include/measurement_kit/common/version.h
include/measurement_kit/common/version.h.in
script/update-includes

Part of https://github.com/ooni/probe-engine/issues/341

Release 0.10.10

---

Doxyfile
configure.ac
include/measurement_kit/common/version.h
include/measurement_kit/common/version.h.in
include/measurement_kit/internal/vendor/http_parser.h
include/measurement_kit/internal/vendor/mkmmdb.hpp
include/private/catch.hpp
m4/mk.m4
script/autogen.d/geoip
script/update-includes
script/vendor/catch
script/vendor/http_parser
script/vendor/mkmmdb
src/libmeasurement_kit/nettests/runnable.cpp
src/libmeasurement_kit/vendor/http_parser.c
src/libmeasurement_kit/vendor/mkcurl.cpp
src/libmeasurement_kit/vendor/mkiplookup.cpp

This helps to address https://github.com/measurement-kit/measurement-kit/issues/1911 and https://github.com/ooni/probe-engine/issues/334.

Release 0.10.11

---

Doxyfile
configure.ac
include/measurement_kit/common/version.h
include/measurement_kit/common/version.h.in
script/update-includes

Part of https://github.com/ooni/probe-engine/issues/809

Release v0.10.12
