measurement-kit/measurement-kit

src/common/pointer.hpp, src/protocols/http.hpp, test/protocols/http.cpp
This pull request fixes a 'corrupted stack' error in http::Stream that leads to a crash. The crash reason is quite stupid (once I realized it); http::Stream shall not be allocated on the stack because its `this` is captured by a few lambdas. Therefore, after http::Stream is moved, the captured `this` is no longer valid.
Fix by using SharedPointer and allocating http::Stream on the heap.
=> Fix http stream corrupted stack

.gitignore, src/common/pointer.hpp, test/common/pointer.cpp, test/include.am
This pull request adds the `SharedPointer<T>` template smart pointer. This extends the standard `std::shared_ptr<T>` to check whether the pointee is `nullptr` each time the pointer is accessed. The way in which `SharedPointer<T>` is implemented is such that you can assign it the result of the standard `std::make_shared<T>()` function template.
I have already used the `SharedPointer<T>` template to fix a couple of bugs in pull requests #60 and #61.
=> Add SharedPointer<T> smart pointer

src/common/check_connectivity.hpp, src/common/constraints.hpp, src/common/libevent.h, src/common/pointer.hpp, src/common/poller.h, src/common/stringvector.h, src/net/connection.cpp, src/net/connection.h, src/ooni/net_test.cpp, src/ooni/net_test.hpp, test/common/bufferevent.cpp, test/common/delayed_call.cpp, test/common/evbuffer.cpp, test/common/poller.cpp, test/net/buffer.cpp, test/protocols/dns.cpp
I was using move semantic in an error prone way. Hand-writing move constructor and move-assignment operator leads to errors when one forgets to update them *and* a new field is added (see #61 and in particular 78fc5d122ec and 5c221b47278).
Also, when there are lambdas bound to an object's `this`, either the object must be created on the heap or the lambdas must be recreated after each move (see again #61, in particular 097d1b5a3a8a and 72ea0117539). In this case the problem is that making an object movable encourages one to create it on the stack, which is exactly what should not happen.
Thinking a bit more on move semantic, I've come to the conclusion that  we should rely on the compiler's move semantic for simpler objects. As regards complex objects, we should make them non copyable and …
=> Start to fix move semantic

src/ooni/dns_test.cpp, src/ooni/dns_test.hpp, src/protocols/dns.cpp, src/protocols/dns.hpp, test/protocols/dns.cpp
Remove hand-rolled move semantic. Use compiler-provided copy and move implementation for objects that don't contain pointers to C structures and/or lambdas. Otherwise, disable copy and move and, when copy and move are needed, allocate on the heap using SharedPointer.
=> Fix dns move semantic

src/net/buffer.hpp, src/net/connection.h, src/ooni/tcp_test.cpp, src/ooni/tcp_test.hpp, src/protocols/http.hpp, test/echo_client_evbuf.cpp, test/net/buffer.cpp, test/net/connection.cpp, test/protocols/http.cpp
This fixes the move semantic in `src/net`. If an object does not contain pointers to C structures allocated on the help and does not contain lambdas bound to this and does not contain callbacks, make it copyable and movable. Otherwise, make it non copyable and non movable and, when we need to copy and/or move it, allocate it on the heap and manage its lifecycle using a SharedPointer.
=> Fix net move semantic

src/common/libevent.h, src/net/connection.cpp, src/net/connection.h, test/common/bufferevent.cpp, test/net/connection.cpp
Before implementing socks5, I dedicated some love to connection to simplify it a bit. In perspective the changes in this pull request should allow to avoid the complete wrapping of IghtConnectionState using IghtConnection.
=> Simplify connection by removing its delayed close

src/common/libevent.h, src/net/connection.cpp, src/net/connection.h, test/common/bufferevent.cpp, test/net/connection.cpp
Do not manage the socket separately. I've checked that libevent is robust with respect to calling close(-1) when the filedescriptor is not set for a long time now.
=> Connection: no separately managed socket

src/common/libevent.h, src/net/buffer.cpp, src/net/buffer.hpp, src/net/connection.cpp, src/net/connection.h, src/net/connection.hpp, src/net/include.am, src/net/socks5.cpp, src/net/socks5.hpp, src/net/transport.cpp, src/net/transport.hpp, src/ooni/tcp_test.cpp, src/ooni/tcp_test.hpp, src/protocols/http.cpp, src/protocols/http.hpp, test/common/bufferevent.cpp, test/echo_client_evbuf.cpp, test/net/connection.cpp, test/protocols/http.cpp
This is done by introducing Transport, a new abstraction, from which both socks5 and the old connection derive. Then, when you create a transport, you can specify whether to use socks5 or not. Depending on your choice, the connection code or the socks5 code is picked up.
=> Implement socks5

src/ooni/http_test.hpp, src/ooni/net_test.hpp, src/ooni/tcp_test.hpp
Stuff spotted while working on another branch:
1) make sure headers have distinct include guards so that all headers can be successfully included by the same source file;
2) make `NetTest` destructor virtual to avoid a compiler warning.
=> Fixes for src/ooni headers

src/protocols/http.hpp
Apparently (but, to be honest, I don't fully understand why) it is not safe to pass a function in the closure of another function.
That is, the safest patter that we should use is to pass only `this` into the closure of a callback.
Before this commit:
$ valgrind --leak-check=full ./test/protocols/http "HTTP stream works as expected"
==24200== Memcheck, a memory error detector
==24200== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==24200== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==24200== Command: ./test/protocols/http HTTP\ stream\ works\ as\ expected
==24200==
===============================================================================
test cases: 1 | 1 passed
assertions: - none -
==24200==
==24200== HEAP SUMMARY:
==24200==     in use …
=> Plug memleak in src/protocols/http.hpp

src/ooni/dns_injection.cpp, src/ooni/dns_injection.hpp
Following up from #77. My understanding is now slightly increased: it's not that passing `std::function<>` as lambad's `[]` context is something that, in general, causes memory leaks. This only happens in some cases. For example, in this case to plug the leak it was enough to fix DNS injection usage of lambdas, without touching `net_test.cpp`.
Before this commit:
==28014== Memcheck, a memory error detector
==28014== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==28014== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==28014== Command: ./test/ooni/dns_injection
==28014==
Found input file
Running next measurement
Getting next line
Returning new line
Creating entry
Calling setup
Running with input torproject.org
dns - IPv4
dns - adding …
=> Plug all memory leaks in dns_injection

src/ooni/tcp_connect.cpp, src/ooni/tcp_connect.hpp
Following up from #77 and #78, let's plug more leaks. All these leak-plugging commits will help me to debug other memory errors that I am seeing in other branches.
Before this commit:
==32409== Memcheck, a memory error detector
==32409== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==32409== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==32409== Command: ./test/ooni/tcp_connect
==32409==
Found input file
Running next measurement
Getting next line
Returning new line
Creating entry
Calling setup
Running with input torproject.org
utils:ight_timeval_init - enter
utils:ight_timeval_init - ok
dns - IPv4
dns - adding '86.59.30.40'
dns - adding '93.95.227.222'
dns - adding '154.35.132.70'
dns - adding '38.229.72.16'
dns - adding '82.195.75.101' …
=> Fix memleak in tcp_connect

src/protocols/http.cpp, test/protocols/http.cpp
Spotted by working on #80. Before this pull request, the internal parser object was leaked if an exception was thrown while parsing (either because a parse error or because the `upgrade` header was seen).
=> HTTP parser: prevent leak on parse error or upgrade

src/protocols/http.cpp, test/protocols/http.cpp
When HTTP parser receives EOF, `http_parser_execute()` is called. This function, in turn, may invoke callbacks that may destroy the parser.
Improve the code robustness by delaying destruction until the parser is ended.
Prevents accessing non allocated memory because after `http_parser_execute()` returns there is still code that is executed.
=> Make HTTP parser robust with respect to EOF

src/net/connection.hpp, src/net/socks5.hpp, src/net/transport.hpp, src/protocols/http.cpp, src/protocols/http.hpp, test/protocols/http.cpp
Based on #81, this pull request is related to #80. Here we make sure that, when EOF is received, http::Request callback is called once rather than twice.
=> Make sure http::Request callback is called only once on EOF

.gitignore, .travis.yml, Makefile.am, configure.ac, include/ight/common/async.hpp, include/ight/common/libevent.h, include/ight/common/net_test.hpp, include/ight/common/pointer.hpp, include/ight/common/poller.h, include/ight/net/dumb.hpp, include/ight/ooni/net_test.hpp, include/ight/protocols/http.hpp, src/common/async.cpp, src/common/include.am, src/common/poller.cpp, src/ext/include.am, src/net/include.am, src/net/transport.cpp, src/ooni/net_test.cpp, test/common/async.cpp, test/include.am, test/protocols/http.cpp
This pull request contains the patches needed to move forward iOS application development:
1) bugfix of an use after free bug without which the code to run tests in a background thread (see 3) experienced occasional crashes
2) code needed by the libight-build-ios repository to generate a directory containing libight and all its dependencies libraries and headers without which we cannot recompile a libight for iOS including the code described in 3
3) code to run tests in a background thread that is needed to move forward the iOS app development
Regarding 3, it still needs some love (for example, there are leaks that I am investigating) but before making it perfect I'd say let's merge it and use it in the App to see whether it fullfills our needs.
=> Patches needed to move forward iOS application development

.travis.yml, configure.ac, src/net/connection.cpp, src/net/transport.cpp, test/protocols/http.cpp
This pull request fixes a crash caused by used after free in socks5 code when the code was compiled using gcc. Interestingly, everything was OK when the code was compiled with clang. Detailed discussion and plan to mitigate this issue in 8c992d7 commit message.
In addition to this, I've also commited changes that, if applied earlier, would have allowed us to spot this bug. Namely, now we use the default compiler on Linux (as opposed on clang) which leads to use gcc in most cases. Now, we install Tor on travis-ci so that we test socks5 code also on travis-ci with both gcc and clang on Linux.
Finally, while testing all of this I noticed that an HTTP test took more than one minute to complete and I modified it to take less than four seconds.
=> Fix crash when socks5 code is compiled using gcc

src/net/transport.cpp, test/protocols/dns.cpp
This fixes a build error in `src/net/connection.cpp` and deals with the fact that ooni.torproject.org IPv6 address changed breaking some tests. The latter issue was reported to me by @alessandro40.
=> Fix build and tests

Makefile.am, configure.ac
GCC does not implement `-Wmissing-prototypes` therefore teach `./configure` to only set this flag when the compiler supports it (currently, when we se clang).
=> Fix gcc warning

include/ight/common/check_connectivity.hpp, src/common/check_connectivity.cpp
As @bassosimone suggested, the Google public DNS might be blocked
in some countries. So, it is more robust to use the default system
resolver to query for the IP address of nexa.polito.it.
=> Use the system-wide DNS resolver for the connectivity check

.gitmodules, test/include.am
With the following changes merged, I am able to cross-compile libight for Android for ARM, MIPS and android-86 (see [libight-build-android](https://github.com/TheTorProject/libight-build-android)).
After this change, **remember to run** `git submodule sync` because I have changed the URL of boost/core repository to point to our personal fork.
=> Android-NDK-integration changes

.clang-format, .gitignore, include/ight/common/utils.hpp, include/ight/traceroute/android.hpp, include/ight/traceroute/interface.hpp, src/common/utils.cpp, src/include.am, src/traceroute/android.cpp, src/traceroute/include.am, src/traceroute/interface.cpp, test/include.am, test/traceroute/android.cpp
This is same as #117 except that I rebased the branch and squashed commits. I'd rather used #117 but apparently I cannot easily reopen it since I rebased.
---
This code was contributed by developers of Portolan, a network measurement tool developed at University of Pisa.
Many many thanks!
I started merging this code to libight during the Tor winter dev meeting in Valencia, after which I was able to compile it.
Then I worked on this together with @ValerioLuconi during a two day hackfest held in Pisa (27-28 Apr).
Finally I also worked on this on May 21, at Nexa.
This code compiles and runs on Linux, an early version of it was tested it both using IPv6 (at CNR), this version only on IPv4.
The original history of this contribution to libight counted 60+ commits that I have squashed to tidy …
=> Add android traceroute code

src/traceroute/interface.cpp
Add one missing header required by MacOS and use defines that apparently are defined by both MacOS and Linux (saying this since compiling succeeded on both systems).
=> Fix building on MacOSX

test/common/bufferevent.cpp
Silence compiler warning that appeared on Linux.
=> test/common/bufferevent.cpp: silence warning

src/common/async.cpp, test/common/async.cpp
This pull request adjusts async tests to expose a bug (leading to a crash) spotted while working on the iOS application and then fixes the bug (basically, the issue was that I overwrote the thread object before either detaching or joining it).
=> async: adjust tests to expose bug, then fix it

include/ight/traceroute/interface.hpp, src/traceroute/interface.cpp
Fixes "Traceroute common doesn't compile on iOS (device)" issue (measurement-kit/measurement-kit-issues#9). [There are very few headers in the iOS SDK](http://stackoverflow.com/questions/29148341/xcode-fails-to-compile-for-real-ipad-but-works-for-simulator-missing-header-fil), since compiling only the generic interface of traceroute for iOS (or for MacOS for that matter) was not a priority, I took the fast route and just disabled compiling that part of code on any non-linux system.
Compiles on MacOS, compiles on iOS (arm) and I see no reason why it should not compile for other iOS architetures. Will merge right after travis-ci confirm that this builds on Linux as well.
=> Do not build traceroute on non Linux

include/ight/common/async.hpp, src/common/async.cpp, test/common/async.cpp
This should solve the problem described in issue #139, even though the solution implemented here is different from the one suggested in issue's description (but that's irrelevant).
I've tested this on Linux, using valgrind to make sure that except for the leak reported in #138 there are no further memory errors.
Closes #139.
=> Register test complete callback along with test

doc/common/error.md, include/measurement_kit/common/error.hpp, include/measurement_kit/http/http.hpp, include/measurement_kit/ooni/http_test.hpp, src/ooni/tcp_test.cpp, test/echo_client_evbuf.cpp, test/http/http.cpp
Let error encapsulate an integer error and start defining a generic-error class in error.hpp.
Also add manpage-like documentation.
This is part of the release engineering activities that I'm carrying out this weekend.
This pull request is simple-enough to qualify as hotfix. I will merge it shortly after travis-ci confirms that this is possible.
=> Make error really useful

doc/common/check_connectivity.md, include/measurement_kit/common/check_connectivity.hpp, src/common/check_connectivity.cpp, test/dns/dns.cpp, test/http/http.cpp, test/net/connection.cpp
- Rename class CheckConnectivity for consistency
- Move documentation at doc/common/check_connectivity.md
- Modernize coding style
- Propagate changes to regress tests
This is part of the release engineering activities that I'm carrying out this weekend.
This pull request is simple-enough to qualify as hotfix. I will merge it shortly after travis-ci confirms that this is possible.
=> Release engineering of check-connectivity

doc/common/bufferevent.md, doc/common/evbuffer.md, doc/common/libs.md, include/measurement_kit/common.hpp, include/measurement_kit/common/bufferevent.hpp, include/measurement_kit/common/evbuffer.hpp, include/measurement_kit/common/libs.hpp, include/measurement_kit/common/poller.hpp, include/measurement_kit/dns/dns.hpp, include/measurement_kit/net/connection.hpp, include/measurement_kit/ooni/net_test.hpp, src/common/include.am, src/common/poller.cpp, src/dns/dns.cpp, src/ooni/dns_test.cpp, test/common/bufferevent.cpp, test/common/delayed_call.cpp, test/common/evbuffer.cpp, test/common/poller.cpp, test/dns/dns.cpp
- rename libs.hpp and Libs because more than libevent is wrapped
- add documentation
- move BuffereventSocket and Evbuffer to separate headers
- rename BuffereventSocket Bufferevent for consistency
Will merge this as soon as travis-ci confirms that it's possible to proceed
=> Release engineering of libevent.hpp

include/measurement_kit/common/net_test.hpp, src/common/include.am, src/common/net_test.cpp, test/common/async.cpp
- use class, not struct
- rename on_log() for consistency
- rename set_verbose()
- coding style
- move destructor in .cpp file to avoid weak-vtable warning
=> Release engineering of common/net_test.hpp

include/measurement_kit/common/error.hpp
These errors will be useful in future pull requests.
Hotfix to be merged as soon as travis-ci build succeeds.
=> Start to define some errors

README.md
- define capabilities and goals more clearly than before
- mention implemented tests
- mention facilities allowing you to implement your tests
- mention future plans including more ooni tests, oonib interaction, performance tests
=> README.md: improve description

doc/common/pointer.md, include/measurement_kit/common/pointer.hpp, test/common/pointer.cpp
This pull request adds the `get()` method to `SharedPointer`, documentation, and regress tests.
Given its simplicity and the unit test coverage, I'll treat this as an hotfix, and will merge it soon.
=> Document and improve pointer

doc/net/buffer.md, include/measurement_kit/http/http.hpp, include/measurement_kit/net/buffer.hpp, include/measurement_kit/ooni/http_test.hpp, src/http/http.cpp, src/net/buffer.cpp, test/http/http.cpp, test/net/buffer.cpp
This pull request aims to simplify and to make more robust net/buffer code. More details in the individual commit messages. This is what was needed to prepare this part for version 0.1.
=> Improve net/buffer

include/measurement_kit/dns/query.hpp, include/measurement_kit/dns/resolver.hpp, include/measurement_kit/dns/response.hpp, include/measurement_kit/ooni/dns_test.hpp, src/dns/query.cpp, src/dns/query_impl.hpp, src/dns/resolver.cpp, src/dns/response.cpp, src/net/connection.cpp, src/ooni/dns_injection.cpp, src/ooni/dns_test.cpp, test/dns/query.cpp, test/dns/resolver.cpp
1. Use less &&value and less std::move(). Since I don't fully understand what those two C++11 features do in practice, I've decided not to use them. I will do more research after the release to understand whether we need this stuff or not.
2. Save and export response evdns type. Useful to avoid storing context in a lambda in src/connection.cpp
=> More simple dns changes

include/measurement_kit/dns/query.hpp
- forbid copy that will break our code
- explain why
- document need to use default move operations
- document how a simpler implementation would look like
(not reimplementing now, with the pending release and lots of things in the TODO list, due to other priorities. Also this is simple enough to qualify as an hotfix.)
=> Update Query copy/move strategy

include/measurement_kit/common/error.hpp, include/measurement_kit/http/request.hpp, include/measurement_kit/net/buffer.hpp, include/measurement_kit/net/error.hpp, test/http/request.cpp, test/http/stream.cpp
Will be used soon to report errors that more naturally map onto the errors of OONI without too much verbosity required.
=> Support for mapping errors to OONI errors

doc/common/async.md, include/measurement_kit/common/async.hpp, src/common/async.cpp, test/common/async.cpp
This pull request contains the good parts of #160. The part that is not included (i.e. code to avoid running callbacks in background threads) was removed after discussion with @lorenzoPrimi.
Detail of changes in this diff:
- Include what you use and other cosmetics.
- Move private variables at bottom.
- No custom poller to constructor. This is too early in the life of the Async class to have a custom poller.
- Document break_loop().
- Remove on_empty() and instead rely on empty().
- Restructure AsyncState to have variables for each state in the life cycle of a test.
- Add INSERT and GET macro to increase coding correctness.
- In event_loop() reset state->interrupted to false to counter the effect of a previous break_loop().
- Unify the code to break from the loop and make sure we cleanup …
=> Improve async implementation

include/measurement_kit/traceroute/android.hpp, include/measurement_kit/traceroute/interface.hpp, src/traceroute/android.cpp, src/traceroute/interface.cpp, test/traceroute/android.cpp
<strike>This needs some **more testing before it can be merged**. However I'm opening a pull request to bind it to the upcoming milestone and know this is something to work on.</strike>
This has now been refined and moderately tested. Note that this is needed by *Portolan*.
=> Teach portolan traceroute about reply packets.

include/measurement_kit/net/connection.hpp, src/net/connection.cpp, test/net/connection.cpp
This should be part of MeasurementKit 0.1.0. Before it can be merged, it should be rebased and the conflicts below should be solved. This is needed by *Portolan*.
=> Allow connection with custom poller

mobile/android/scripts/build.sh, scripts/update-deps.sh, src/ext/libevent/.gitignore, src/ext/libevent/Makefile.am, src/ext/libevent/configure.ac, src/ext/libevent/evutil_rand.c
This pull request has been updated and now only contains:
- changes in Makefile.am to reduce the compile time to recompile libevent for Android and iOS (rationale: we're integrating libevent, we're not developing it)
- the [arc4random_addrandom fix v2](https://github.com/measurement-kit/libevent/commit/8b275d967d7ffd95d5cc12069aef35669126c6d9) fix, needed to compile on Android under most architectures
- a revert for e7ea40bd9ad so that all Android architectures are built
To test this diff, I suggest to take the low-level approach of recompiling everything:
```
make distclean
git clean -dfx
cd mobile/android
./scripts/build.sh /path/to/ndk 21
```
and then do the following for each architecture:
- check `build/$arch/config.h` and see whether `arc4random` and `arc4random_addrandom` are …
=> Modify libevent to compile for all Android archs

mobile/android/README.md, mobile/android/scripts/build.sh, mobile/android/scripts/build_target.sh
To test this, verify that by running `./mobile/android/scripts/build.sh $ndkpath` you recompile all the architectures available for Android without issues.
=> Improve android build scripts

include/measurement_kit/traceroute/android.hpp, src/traceroute/android.cpp
AndroidProber constructor body is empty. Errors are passed to error_cb_ by init function.
With gcc 5.2.0  this warning are shown:
```
src/traceroute/interface.cpp: In member function ‘measurement_kit::traceroute::ProbeResultMeaning measurement_kit::traceroute::ProbeResult::get_meaning()’:
src/traceroute/interface.cpp:77:72: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘measurement_kit::traceroute::ProbeResultMeaning’ [-Wformat=]
icmp_type, icmp_code, PRM_::GOT_REPLY_PACKET);
^
src/traceroute/interface.cpp:84:40: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘measurement_kit::traceroute::ProbeResultMeaning’ [-Wformat=]
m->meaning);
^
src/traceroute/interface.cpp:89:48: warning: format ‘%d’ expects argument of type ‘int’, but …
```
=> traceroute: make constructor lazy 

mobile/ios/scripts/build_arch.sh
Like in [issue-208](https://github.com/measurement-kit/measurement-kit/issues/208).
To make sure that configure use the built-in version instead of the version in the system.
It works. ./configure prints no more this output:
configure: WARNING: No jansson found: will use the builtin jansson
configure: WARNING: No libmaxminddb found: will use the builtin libmaxminddb
Closes #208.
=> Add instructions to use jansson and libmaxminddb

.gitignore, README.md, doc/api/c++/common/var.md, include/measurement_kit/common.hpp, include/measurement_kit/common/async.hpp, include/measurement_kit/common/delayed_call.hpp, include/measurement_kit/common/var.hpp, include/measurement_kit/dns/query.hpp, include/measurement_kit/http/request.hpp, include/measurement_kit/http/stream.hpp, include/measurement_kit/net/connection.hpp, include/measurement_kit/net/transport.hpp, include/measurement_kit/ooni/dns_test.hpp, include/measurement_kit/ooni/net_test.hpp, include/measurement_kit/ooni/tcp_test.hpp, src/common/async.cpp, src/common/include.am, src/dns/query.cpp, src/dns/query_impl.hpp, src/dns/resolver.cpp, test/common/async.cpp, test/common/delayed_call.cpp, test/common/var.cpp, test/dns/query.cpp, test/include.am
The latter is more concise and conveys the meaning that Var<T> has a semantic similar to `var foo` in JavaScript.
=> Rename SharedPointer<T> to Var<T>

include/measurement_kit/common/error.hpp, include/measurement_kit/common/maybe.hpp, test/common/maybe.cpp
`Maybe<type> maybe`  now can be called.
MaybeNotInitializedError() is called when accessing the variable without initialization.
Closes #242
=> Allowed creation of empty maybe.

.gitignore, README.md, doc/api/c++/ooni/dns_injection_test.md, doc/api/c++/ooni/http_invalid_request_line_test.md, doc/api/c++/ooni/tcp_connect_test.md, include/measurement_kit/common/async.hpp, include/measurement_kit/ooni.hpp, include/measurement_kit/ooni/base_test.hpp, include/measurement_kit/ooni/dns_injection_test.hpp, include/measurement_kit/ooni/http_invalid_request_line_test.hpp, include/measurement_kit/ooni/tcp_connect_test.hpp, src/common/async.cpp, src/ooni/base_test.cpp, src/ooni/dns_injection.cpp, src/ooni/http_invalid_request_line.cpp, src/ooni/include.am, src/ooni/tcp_connect.cpp, test/common/async.cpp, test/include.am, test/ooni/dns_injection_test.cpp, test/ooni/http_invalid_request_line_test.cpp, test/ooni/tcp_connect_test.cpp
Tested locally also with Valgrind to make sure this new set of patches does not add memory errors.
This is not enough to close #243, because improvements are needed to allow one to provide a specific poller or async to the code. However, to do so we would need to change the underlying implementation too much, and I don't want to do this before making a release.
=> Teach OONI tests to run themselves

mobile/android/scripts/build_target.sh
Now that MK does not pull dependencies headers from its headers, we do not need anymore to install such headers.
=> android: only install MK headers

test/fixtures/hosts.txt, test/ooni/dns_injection.cpp, test/ooni/dns_injection_test.cpp
This goes as far as possible in fixing #101 without triggering travis-ci errors. While working on this we discovered, in fact, that the http-invalid-request-line test required more massaging to deal with a backend that does not speak http. Further changes to deal with this breakage and finally make sure that all the regress tests use the correct address are in #253.
=> Partial fix for issue 101

.travis.yml, configure.ac, src/ext/include.am, test/common/async.cpp, test/http/client.cpp, test/http/request.cpp, test/http/response_parser.cpp, test/http/stream.cpp, test/net/connection.cpp, test/net/transport.cpp, test/ooni/dns_injection.cpp, test/ooni/dns_injection_test.cpp, test/ooni/http_invalid_request_line.cpp, test/ooni/http_invalid_request_line_test.cpp, test/ooni/tcp_connect.cpp, test/ooni/tcp_connect_test.cpp, test/ooni/tcp_test.cpp
Start to repair coveralls and improve the build process. Work done so far:
- travis: split build command on multiple lines
- configure.ac: recognize clang++
- yaml-cpp: zap -Wno-missing-prototypes flag
- run quiet configure with summary at the end
- revert "Teach travis to send one time the coverage reports"  (712602c5da)
- reduce verbosity of all tests
Work to do before we can merge this pull request:
- apparently coveralls segfaults for gcc builds because of a version mismatch between the compiler (v4.8) and some other unspecified utility (v4.6): find a fix for that
- find a way to teach coveralls to produce less output than this, because this is too much
=> Repair coveralls and improve build process

include/measurement_kit/http/error.hpp, src/http/response_parser.cpp, src/http/response_parser.hpp, src/net/connection.cpp, test/ooni/http_invalid_request_line.cpp, test/ooni/http_invalid_request_line_test.cpp
This diff is the starting point to fix http-invalid-request-line test when the backend used is an echo server rather than a properly working HTTP server.
So far, I've changed the backend address according to what is indicated in #101. Then, I've added code to route errors in the read and write callbacks of the stream. I think this is a better approach than the other branch that I opened, in which I was rewriting too much of HTTP too close to the release.
The diff works (meaning that routing exceptions prevent the exception thrown by the http-parser to terminate the test). However, I think more is needed to have something mergeable.
Specifically:
1. two new errors should be added to `include/measurement_kit/common/error.hpp`: one should represent a runtime exception received when reading, …
=> fix for http-invalid-request-line

src/traceroute/include.am
Spotted while compiling and testing with Portolan.
=> traceroute: install missing header

mobile/android/scripts/build_target.sh
This should be merged after #273. It changes the way in which we compile Android code to squeeze quite significantly the compiled libraries at the price of losing debug symbols.
Closes #266.
=> Reduce compiled library size on android

mobile/android/.gitignore, mobile/android/scripts/build_target.sh, mobile/android/scripts/make_archive.sh
This should be merged after #274. It creates compressed tarballs of the build. I have plans to publish these tarballs along with the release so that Apps can integrate them.
Closes #268.
=> Create tarballs of the Android build

mobile/android/README.md, mobile/android/scripts/build_target.sh, mobile/android/scripts/make_archive.sh
This is same as #278 except that bikeshedding is removed :-)
- - -
- simplify README.md
- document creation of the tarball
- simplify make_archive.sh
- do not call make_archive.sh from build_target.sh
The rationale of these changes is that:
- the compiled libraries are small (around 7 MiB so we can put everything into a single compressed tarball)
- if we do that, it's simpler to sign the tarball and also given how github releases work it's simpler to download a release
=> Improve Android build process

src/net/connection.cpp, src/net/connection.hpp, src/net/emitter.hpp, src/net/socks5.cpp, src/net/socks5.hpp, src/net/transport.cpp
Like we said in the #279, I changed the name of the class to a more fitting one.
=> Change name of Dumb class to Emitter

src/net/connection.hpp
Fix little bug in the class Connection. 
This closes #280
=> Make the class connection non copyable and non movable

doc/api/common/poller.md, include/measurement_kit/common/poller.hpp, src/common/poller.cpp
I need this in the mobile applications. For example, with Android there is no /etc/resolv.conf, and I need a mechanism to specify the name servers to be used by the default evdns-base instance.
Note that in MeasurementKit there is also a custom Resolver object constructed with default parameters, but this is not the same as the evdns-base instance used by the Poller. The latter is, in fact, the instance actually used when running, e.g., OONI tests.
More can be done to improve MeasurementKit with respect to the poller and resolver facilities used when running tests, but this is not the right moment to do so. We are close to a stable release and hence we should make as minimal changes as possible.
=> poller: allow to modify default evdns-base state

include/measurement_kit/common/poller.hpp, src/common/poller.cpp, test/common/poller.cpp
Previously I didn't notice that, when no /etc/resolv.conf is found on the device, libevent sets 127.0.0.1 as resolver.
This is not what we want on Android. Because on Android there is no resolver at 127.0.0.1. Hence add hooks to clear the configured name servers, such that we can start from scratch.
While here, add a regress test case to check that what I would like to do on Android (i.e. clear all nameservers and then force a specific nameserver address) works.
=> Allow to clear DNS servers on Android

doc/tutorial/android.md, doc/tutorial/ios.md, doc/tutorial/unix.md
Closes #269.
- android
- ios
- unix
The actual tutorial for Android is actually a non-tutorial. In fact, it only explains that what the user is looking like is inside the `measurement-kit-android` repository instead.
The iOS tutorial was tested both using Xcode emulator and on a real device.
The C++ tutorial was tested under Ubuntu 15.10.
=> Add tutorials

mobile/android/scripts/build_target.sh, mobile/ios/scripts/build_arch.sh
It turns out that examples cannot be build when cross-compiling for Android for some architectures.
Already tested this. Before merging, I'd also like to check whether the same issue also prevents us from cross-compiling for iOS. So I can fix both issues in the same pull request.
=> Avoid building examples when cross-compiling

.gitignore, doc/api/http/error.md, doc/api/ooni/base_test.md
While there, also teach git to ignore *.swp files created by vim when a file is currently being edited.
Closes #314 and #313.
=> Add missing bits of documentation

src/http/request_serializer.cpp, src/http/response_parser.cpp
`http_parser_init` and `http_parser_settings_init` are used instead of `memset`.
Closes #292
=> http_parser initializer functions used instead of memset.

README.md
While there, make sure that the link used to refer to HTTP client is correct.
=> Mention mlab-ns in README

Makefile.am, configure.ac, doc/index.md, include/measurement_kit/common/version.hpp, measurement_kit.podspec
This PR updates version number.
The patch can be used to locate version number in the project (al least where i found it). 
An exaustive process is still not defined. An update-script or a single file with the version maybe?
Closes #359.
=> Version number updated from 0.1.0 to 0.2.0-alpha

src/net/connection.hpp
You may want to pause reading, for example because too much data is buffered. Now you can do this by passing `nullptr` to the transport's `on_data` method.
=> connection: disable read when callback is null

include/measurement_kit/http.hpp, include/measurement_kit/ooni/base_test.hpp, src/http/client.cpp, src/http/request.hpp, src/http/stream.hpp, src/ooni/dns_test.hpp, src/ooni/http_test.hpp, src/ooni/libooni.cpp, src/ooni/ooni_test.hpp, src/ooni/tcp_test.hpp
Useful in tor code to use tor's poller rather than the default poller.
=> ooni: allow to use specific poller

src/common/delayed_call.cpp, src/ooni/dns_injection_impl.hpp, src/ooni/http_invalid_request_line_impl.hpp, src/ooni/tcp_connect_impl.hpp, src/ooni/tcp_test_impl.hpp, src/report/base_reporter.hpp, test/ooni/tcp_test.cpp
- make sure that there are no circular references in ooni implementation
- stop being interested in events when they are fired, such that we remove circular references
- make sure delayed call correctly clears its callback
I have already reviewed and approved this pull request offline, discussing it with @AntonioLangiu and adding one further fix to keep valgrind calm. Will merge as soon as travis completes.
=> Fix several circular references

doc/codying-style.md
Hi @hellais, could you review this pull request in which I try to explain measurement-kit's pattern of using functions as opposed to objects in certain cases?
=> Document call_later()'s design pattern

doc/api/common/poller.md, include/measurement_kit/common/poller.hpp, src/common/poller.cpp, test/common/poller.cpp
This contains poller-related changes that are required by #390.
1. implement call_later()
2. make sure event-loop does not exit
3. deprecate loop_once()
The deprecation of loop_once() is because after #390 that functionality becomes unused.
=> Update poller implementation to prepare for #390

.travis.yml
I have implemented a build matrix for the Travis-ci script. Now we are able to test the build with different systems (Ubuntu 12.04, Ubuntu 14.04, MacOSX, iOS). There are 11 different builds with a combination of OS and compiler, but maybe they are too much now. What do you think @bassosimone?
The first three build are done in a container environment, so they should [start immediately and with more resources](https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/), and the other are not in a container and can use sudo, they need approximately 2/3 minutes to start.
=> travis: create build matrix

.travis.yml
Spotted by me and fixed by @AntonioLangiu. Move the if down otherwise the if steals the success/failure bit set by the build and the build does not actually fail.
In the future we should use external script for this. Relying on travis.yml is way too fragile.
=> travis: fix error checking

.clang-format
1) do not collapse short ifs on a single line because that
does not allow us to understand if they're covered
2) change formatting after open braces for long lines in
a way that makes lambdas more readable and that causes
less line diffs when we modify and then clang-format
=> clang-format: improve format

include/measurement_kit/common/poller.hpp
This is useful because there are many cases in the regress tests
in which we want something to happen and then in the corresponding
callback we break the loop. For example,
```C++
net::connect("130.192.91.211", 80, [](Error err) {
REQUIRE(!err);
break_loop();
});
loop();
```
What happens is that sometimes `net::connect()` calls its callback
immediately, when the connection obviously fails.
Unfortunately in that case `break_loop()` would be called before
`loop()` which means that, as libevent does not cope well with this
case and in particular it happens that the loop runs forever.
Since this is mainly an issue with tests, I propose the following:
```C++
loop_with_initial_event([]() {
net::connect("130.192.91.211", 80, [](Error err) {
REQUIRE(!err);
break_loop();
});
});
```
This combines …
=> poller: add loop() with initial event

.gitignore, include/measurement_kit/net/transport.hpp, src/net/emitter.hpp, src/net/transport.cpp, src/net/transport_interface.hpp
Move the TransportInterface definition in a private header and let users of Transport only pull the bare minimum they need.
While there also commit the updated .gitignore file which features more recently added tests. This was updated when I run `./autogen.sh`.
=> Increase net/transport abstraction

src/net/socks5.cpp, src/net/socks5.hpp
Preparatory change for a subsequent pull request in which I will
teach the Socks5 class to attach to an already connected Var<Transport>.
This will go in a separate pull request because the diff is huge (even
though the `diff -w` is trivial).
=> socks5: separate connect() and after-connect()

include/measurement_kit/net/error.hpp, src/http/request.hpp, src/http/stream.hpp, src/net/connection.cpp, src/net/connection.hpp, test/http/stream.cpp
While there: s/EOFError/EofError/g (I will gradually remove acronyms from class names; I think that EofError is more readable).
=> connection: use extern-C for libevent callbacks

.gitignore, include/measurement_kit/net/transport.hpp, src/http/stream.hpp, src/net/connection.hpp, src/net/emitter.hpp, src/net/socks5.cpp, src/net/socks5.hpp, test/net/connection.cpp, test/net/emitter.cpp
Closes #102.
To make sure I was not doing mistakes in this diff, I renamed the transport's functions to send as write() and the actual function used to implement send as do_send(). This way the compiler helped me to find out all the places where refactoring was needed.
Besides, given Twisted, I prefer `transport.write` to `send` :-).
=> Teach transport to record received/sent bytes

include/measurement_kit/net/buffer.hpp, src/net/buffer.cpp, src/net/evbuffer.hpp, test/net/buffer.cpp, test/net/evbuffer.cpp
Replace the Evbuffer non-copyable, non-movable RAII evbuffer wrapper class with a Var<evbuffer> with correctly set deleter func.
Reduces the number of lines of code used and adds copyability and movability to the thing contained underlying a Buffer.
Also, make the Var<evbuffer> public such that one can access it easily if needed (this helps to call low-level libevent operations).
Also, deploy more curly braces here and there.
=> buffer: s/Evbuffer/Var<evbuffer>/g

include/measurement_kit/http/http.hpp, src/http/request.hpp, src/http/response_parser.cpp, src/http/response_parser.hpp, src/http/stream.hpp, test/http/response_parser.cpp
Mainly use less specific includes, reduce excess documentation, and apply simple cosmetic fixes to the code.
=> simple http cleanups

doc/private/http/response_parser.md, src/http/request_serializer.hpp, src/http/response_parser.hpp
HTTP code was overdocumented. Start removing some excess documentation and make sure that we end up with good bits below `docs/`.
=> http: remove excess documentation

.gitignore, autogen.sh, build/dependency, build/patch/http-parser/000.diff, build/patch/yaml-cpp/000.diff, build/spec/Catch, build/spec/all, build/spec/boost, build/spec/http-parser, build/spec/jansson, build/spec/libevent, build/spec/libmaxminddb, build/spec/libressl, build/spec/yaml-cpp
In this PR I'm integrating the work of @bassosimone in [this branch](https://github.com/measurement-kit/measurement-kit/tree/feature/build-improvements).
Pratically, now we are able to build a single dependency, with a script that downloads it from a git repository and builds it inside a defined folder.
To see more details check the script [./build/dependency](https://github.com/measurement-kit/measurement-kit/blob/feature/build/build/dependency)
=> Add single dependency build script 

.travis.yml
I'm readding the test folder to the coverall check. I don't know why but without it the coveralls calculation is not correct. 
I think the examples folder should not be included!
[This](https://coveralls.io/builds/5711030/source?filename=include%2Fmeasurement_kit%2Fdns%2Fdns.hpp) is an example of the falsh calculation without the tests example! The code seems not tested, but it is is [test/dns/defines](https://github.com/measurement-kit/measurement-kit/blob/master/test/dns/defines.cpp)
=> readd the tests folder to coveralls

include/measurement_kit/net/error.hpp, src/net/connect.cpp, src/net/connection.cpp
I need this in master to improve error checking when tor is not running in #451. While at it, rename `DNSGenericError()` to `DnsGenericError()` which is more readable.
=> connect: use slightly more specific errors

test/net/buffer.cpp
This was of the memory errors spotted in #452.
=> test/net/buffer.cpp: fix memleak

include/measurement_kit/http/http.hpp, src/http/client.cpp, src/http/request.cpp, src/ooni/http_test_impl.hpp, test/http/client.cpp
First pull request in a wave of pull requests for cleaning up MK after recent changes in DNS, net, and HTTP code that improved API safety and ease of usage.
Here we take down the HTTP client, refactor existing tests, and mark with XXX and/or TODO places in the code that need further love.
Before we proceed, it seems there are [memory errors introduced by this cleanup](https://travis-ci.org/measurement-kit/measurement-kit/jobs/122739892#L3075).
=> Big cleanup: remove http/client

test/http/client.cpp, test/http/funcs.cpp, test/http/request.cpp, test/http/stream.cpp
The objective here is to avoid losing coverage but to arrive to
a point where there are no test cases for old HTTP API.
At that point, we can then safely remove such API without causing
any issue to the tree, because no users are left.
- convert Request() test cases to use request(), but skip for now
the test cases where such conversion is not straightforward
- remove Stream() test cases that duplicate test cases that use
the request() API (no point in converting them)
- note that there is more work to do
=> big cleanup: convert, remove http test cases

src/net/transport.cpp, test/http/request.cpp, test/http/stream.cpp
This adapts t/h/request.cpp test checking for EOF to use the
new, rather than the old, request API.
While there, also get rid of the corresponding http/stream.cpp
test, given that http::Stream will be removed soon.
=> t/h/request.cpp: adapt test checking for EOF

src/http/request.cpp, src/http/request.hpp, test/http/request.cpp
Refactor tor_socks_port tests not to depend on the previous
implementation of http::Request. To this end, I needed to move
http::request_connect() is src/http/request.hpp and refactor
it to become a template that we can override for testing.
=> http: refactor tor_socks_port tests

src/net/connect.cpp, src/net/connect.hpp, src/net/connection.cpp, src/net/connection.hpp, src/net/transport.cpp, test/net/transport.cpp
To achieve this goal, I needed to implement the following changes:
1) src/net/connect.cpp: teach resolve_hostname() about the
possibility of using a custom poller and, when this function,
is invoked by connect(), forward to resolve_hostname() the
poller that was passed to connect()
2) src/net/connection.cpp: make sure the constructor that
receives a bufferevent also allows to set a custom poller
and a custom logger
3) src/net/transport.cpp: make sure we pass possibly custom
poller and logger when constructing Connection
4) src/net/transport.cpp: make sure that we set a timeout when
connecting and also, just in case, after connected
5) test/net/transport.cpp: make sure that the net::connect()
that takes a callback works with a custom poller
=> Teach net::connect(..., cb) about custom pollers

src/net/connection.hpp
<strike>Use MK_MOCK() to allow to override specific functions of
Connection for debugging purposes.</strike>
Remove some methods that actually are unused.
=> connection.hpp: remove unused methods

.clang-format, configure.ac
1) .clang-format: undo recent style changes
@DavideAllavena and I recently tried to introduce some style
changes, but after testing them for a while, I come to the
conclusion that the previous style was more readable and clear.
2) remove nonexistent macros from configure.ac
Most likely that those are a leftover of the recent diff by @AntonioLangiu 
that removed from the tree yaml-cpp and boost.
=> Tweaks developed while working on s/n/connection

example/net/listen.cpp, src/net/connection.cpp, src/net/connection.hpp, src/net/socks5.cpp, src/net/transport.cpp
1) make Connection() private and introduce a factory called make() to
return a Var<Transport> instead and propagate changes
2) introduce static methods that shall deal with events generated
by libevent and call existing non static methods
3) introduce safe_upcall() macro to implement said methods, for now
with a very trivial implementation
4) add Poller * member which will be used soon
=> net: preparatory changes for #484

example/net/listen.cpp, example/net/transport.cpp, include/measurement_kit/net/transport.hpp, src/http/request.cpp, src/net/connection.cpp, src/net/connection.hpp, src/net/emitter.hpp, src/net/socks5.hpp, src/ooni/tcp_connect_impl.hpp, test/net/connection.cpp
This is the starting point to implement #484. Further refinements are making the transport self aware so that one does not need to keep it alive in the close callback, and write post-close unit tests.
=> transport: now close takes a callback

src/net/connection.cpp, src/net/connection.hpp
While there also simplify code by removing some complexity added in #488 that I though was needed to implement #489 but that eventually turned out to be unnecessary because I took a simpler path where garbage collection is not needed :-).
=> connection: call close callback in destructor

example/http/request.cpp, example/net/transport.cpp, src/common/utils.cpp, src/http/parse_url.cpp, src/http/request.hpp, src/mlabns/mlabns.cpp, src/net/connect.cpp, src/net/connect.hpp, src/net/ssl-context.cpp, src/net/ssl-context.hpp, src/net/transport.cpp, test/http/request.cpp, test/net/transport.cpp
This is very rough. In particular, we do not validate certificates, so
a man in the middle is very possible for now.
But I feel like it's important to have the basic scaffolding such
that things that should go in parallel over SSL can.
<strike>Crossing fingers as for Valgrind. I recall that used to reported
several uninitialized variables in OpenSSL.</strike>
=> Add initial SSL implementation

src/dns/query.hpp
As found by @bassosimone, we didn't consider the case a user callback throws an exception. 
I think this should fix the problem and catch all the exception. 
@bassosimone do you know how to test if the context has been really deleted? 
This closes #481
=> Make dns callback robust to exceptions

include/measurement_kit/common/logger.hpp, include/measurement_kit/common/poller.hpp, include/measurement_kit/traceroute/android.hpp
Closes #111.
Not ready yet. Started working on this with @AntonioLangiu and created a template function that provides syntactic sugar for calling std::functions as demonstrated in #111. More work to be done before we can actually merge this into master. Specifically:
- need to check existing code
- need to use safe_call() in all the places in which a std::function is bound to an object that allows with another method to set the value of the std::function itself
- verify with valgrind
- possibly write more regress tests
=> allow to set std::function<> from a lambda stored inside such function

.travis.yml, README.md, acinclude.m4, build/spec/all, src/ext/include.am
Space changes, removal of spaces at EOL, reindents. In particular, remove
from `./build/spec/all` things for which we do not have a spec.
=> Hotfixes backported from #366

Makefile.am, configure.ac
I do not exactly recall the precise reason, but I remember that
setting pthreads earliers helped me when working to #366.
Backport this specific part of #366 such that, once this is
merged into master, I can focus on the remainder.
=> build system: set pthreads earliers

example/net/connect.cpp, include/measurement_kit/common/error.hpp, include/measurement_kit/net/transport.hpp, src/net/connect.cpp, src/net/connect.hpp, src/net/socks5.cpp, src/net/transport.cpp, test/net/connect.cpp, test/net/transport.cpp
This diff extends the Error class to allow the programmer to add
an error context object to the class, ErrorContext.
Inside the Error, the ErrorContext class is stored using a Var
smart pointer, thus allowing up/downcasting using subclasses.
Then, teach the connect machinery to store a summary of all what
happened during the connection attempt inside the error using
the functionality described above.
Closes #28.
Output of example runs:
```
$ ./example/net/connect -p 81 www.kernel.org
Overall connect result: 1003
input was valid ipv4: 0
input was valid ipv6: 0
ipv4 resolve error: 0
ipv6 resolve error: 0
list of addresses returned:
- 198.145.20.140
- 199.204.44.194
- 149.20.4.69
- 2001:4f8:1:10:0:1991:8:25
- 2620:3:c000:a:0:1991:8:25
errors returned by the various connects:
- 1001
- 1011
- …
```
=> connect: pass to callback info on dns resolution etc

build/dependency, build/patch/libressl/0001-build-just-needed-subdir.patch
Add libressl patch to build just the target we need.
This patch needs to be applied to Makefile.am, and so I moved the patching part of the script after the autogen.sh
=> Add libressl patch 

build/ios/scripts/build_arch.sh, build/ios/scripts/build_frameworks.sh, build/spec/geoip
This is the smallest set of changes from #514 that allow to build all the dependencies, including libressl, for iOS and the iOS emulator. Detail of changes:
1. need to define EXTRA_CONFIG also when using the emulator to ensure dependencies' `./configure` knows we're cross compiling
2. forward `pkg_foo` variables for `./build/dependency`
3. call `./build/dependency` to ensure we have dependencies at the beginning of each build loop
4. tell `./configure` where dependencies are
5. make sure we create all frameworks
6. make sure we can cross compile GeoIP by setting variables that affect its `./configure`
=> Repair build of iOS frameworks

build/spec/libressl
In general, I'd rather pick and use the latest stable version
rather than master. Starting doing that for libressl.
=> build/spec/libressl: use latest stable version

include/measurement_kit/common/poller.hpp, include/measurement_kit/dns/dns.hpp, include/measurement_kit/traceroute/android.hpp, include/measurement_kit/traceroute/interface.hpp, src/common/poller.cpp, src/dns/query.hpp, src/net/listen.hpp, test/common/poller.cpp, test/dns/query.cpp
1) remove get_global_xxx() syntactic sugar
2) remove the evdns_base bound with the poller since now we always
use a custom evdns_base when we do dns requests
3) undeprecate loop_once(): we are not going to rewrite async
to use an always on thread anytime soon
=> poller: remove obsolete code

include/measurement_kit/common/logger.hpp, src/common/logger.cpp
1) do not inline log functions because they're not so short
2) use macros to reduce implementation redundancy
=> Improve logger implementation

src/common/poller.cpp, src/common/poller.hpp
This refactoring is functional to templatize the implementation for
debugging purposes and hence for removing libs.hpp.
=> poller: move implementation in header

src/common/utils.cpp, src/common/utils.hpp, test/common/utils.cpp
A list is more practical given that we are going to remove
from the front of the list inside of NDT code.
=> utils: change split to return a list

src/common/poller.hpp, test/common/poller.cpp
sigaction() is the correct function to invoke, signal() is the obsolete interface
=> poller: use sigaction() rather than signal()

include/measurement_kit/common/error.hpp, include/measurement_kit/dns/dns.hpp, include/measurement_kit/http/http.hpp, include/measurement_kit/mlabns/mlabns.hpp, include/measurement_kit/net/error.hpp, include/measurement_kit/traceroute/error.hpp
Substitutions mechanically performed with this tool:
```python
import re
import sys
REGEX1 = r"///\s*[A-Za-z0-9 .]+\n+class\s+[A-za-z0-9]+\s*:\s*public\s+Error\s*{\n+\s*public\s*:\n+\s*([A-Za-z0-9]+)\s*\(\)\s*:\s*Error\(([0-9]+)\s*,\s*(\"[A-Za-z0-9_\s]+\")\s*\)\s*{\s*}\s*;?\s*(\s*///<\s*[A-Za-z0-9_\s-]*)?\n\s*};\n"
REGEX2 = r"///\s*[A-Za-z0-9 .]+\n+class\s+[A-za-z0-9]+\s*:\s*public\s+Error\s*{\n+\s*public\s*:\n+\s*///[A-Za-z0-9-\s]+\n\s*([A-Za-z0-9]+)\s*\(\)\s*:\s*Error\(([0-9]+)\s*,\s*(\"[A-Za-z0-9_\s]+\")\s*\)\s*{\s*}\s*;?\s*(\s*///<\s*[A-Za-z0-9_\s-]*)?\n\s*};\n"
REGEX3 = r"class\s+[A-za-z0-9]+\s*:\s*public\s+Error\s*{\n+\s*public\s*:\n+\s*([A-Za-z0-9]+)\s*\(\)\s*:\s*Error\(([0-9]+)\s*,\s*(\"[A-Za-z0-9_\s]+\")\s*\)\s*{\s*}\s*;?\s*(\s*///<\s*[A-Za-z0-9_\s-]*)?\n\s*};\n"
REGEX4 = …
```
=> Use macros to define errors

include/measurement_kit/common/error.hpp, include/measurement_kit/common/mock.hpp, include/measurement_kit/mlabns/mlabns.hpp, src/mlabns/mlabns.cpp
1) allow an error to contain a lower level error
2) define `MockedError`: this is the error value that should be
used in regress tests when generic failure is mocked
3) add and use json parsing and access errors: those are generic and
hence they should stay in common
4) allow mock with suffix to mock different invocation of the same
function within a template
5) propagate changes described in 3) to mlabns code
=> Backport changes from NDT branch

include/measurement_kit/common/error.hpp
1) make attributes public because this simplifies writing other
pieces of code and because this is not Java
2) do not touch accessors for now because I appreciate their
semantic (especially `as_ooni_error()`)
3) disable automatic conversion to `int`, which probably was evil, and
only allow evaluation in boolean context
All tests passing locally except mlabns because MPX WiFi does DNS
injection and "8.8.8.1" resolves :^)
=> error.hpp: minor refactoring

src/common/net_test_dsl.cpp
Instead of blocking the thread usign a sleep, a better solution is to use some thread synchronization methods, like std::promise and std::future.
=> Remove polling while running synchronous tests

acinclude.m4, configure.ac
Prodded by @AntonioLangiu.
I have omitted the action to be performed when cross compiling, under the assumption that omitting the action leads to executing the main action specified by the macro also when cross compiling.
If my assumption is wrong, then perhaps this diff is broken. I shall now check whether this works by cross-compiling MK for iOS and then update on that in a short while.
- - - 
Update: the assumption was OK. Cross compiling for iOS went straight on.
=> configure: add -pthread to flags only when needed

src/ooni/ooni_test_impl.hpp
[NetTest is already non-copyable and non-movable](https://github.com/measurement-kit/measurement-kit/blob/master/include/measurement_kit/common/net_test.hpp#L18), so it would be redundant to declare it as non-copyable and movable.
Closes #343.
=> Remove redundant declarations

acinclude.m4
As discussed with @bassosimone, we think that the build fase should fail if the configure is not able to find a ca-bundle.
This will not be checked when cross-compiling!
When testing this pull request I noticed that when cross-compiling for iOS we build for different architectures, and when we build for the `iphonesimulator` the system detect it as not cross-compiling, so the ca-bundle will be searched in the default directories of OSX. I think this should not be a problem because the applications should give a local ca-bundle inside the package, and the iphonesimulator will take that, but I think this is a good thing to know in case of future problems!
=> Fail the configure if the ca-bundle is not found

acinclude.m4, configure.ac
This reverts commit 6ceb9e875741b1cd18f92cf520a6e9ab82e749d8 because it
was the wrong way to address the issue, unfortunately.
The warning was still present. Then, I further investigated and understood
that the way in which clang for OSX deals with -pthread is different from the
way in which the same flag is dealt with on Linux systems.
Given than the matter is more complex than I thought and that the warning
for the -pthread flag only provides some annoyance, I am reverting to before
pull request #607. We will perhaps give another stab at it, but for now
let's ignore the problem, because it's not so important.
=> Revert "configure: add -pthread to flags only when needed (#607)"

src/ooni/dns_injection_impl.hpp, src/ooni/ooni_test_impl.hpp, src/ooni/tcp_connect_impl.hpp
Since it is a class method that shall operate on the attribute
called `input_filepath_`, so need to pass such attribute explicitly
as argument, since it can already access it using `this`.
=> validate_input_filepath() doesn't need arguments

src/ooni/ooni_test_impl.hpp, src/report/base_reporter.cpp, src/report/base_reporter.hpp, src/report/file_reporter.cpp, src/report/file_reporter.hpp, test/report/file.cpp
0) recognize that it's not easily possible to make the report public
without adding nlohmann/json to the public API [*]
1) give headers private include guards since they are private
2) rename writeEntry as write_entry for consistency
[*] This does not appear in the diff. But think about the changes you do
not see in this diff. They are because of that.
=> Cleanup report implementation

include/measurement_kit/common/error.hpp, test/common/error.cpp
Okay, currently we have the reason which is equal to `ooni_error` but
that would not necessarily be the case in future.
So, leave `as_ooni_error()` as the preferred way to know the OONI error
string and use `reason` (more neutral) for the attribute.
=> Error: do not call reason `ooni_error`

include/measurement_kit/common/error_or.hpp, test/common/error_or.cpp
The empty constructor and the constructor with both error and value are
both scarcely if not used. Hence, remove them.
=> error_or: remove unused constructors

include/measurement_kit/http/http.hpp
I have experimented a bit with doxygen but increasingly feel like
it adds noise to the signal / noise ratio.
I'd rather spend time to maintain documentation in `doc/`.
=> http: start cleanup by removing doxygen style docs

include/measurement_kit/http/http.hpp, src/mlabns/mlabns_impl.hpp, src/ooni/utils.hpp, test/mlabns/mlabns.cpp
From the #consistency dept. Another diff is due to make sure
the same holds in net. But not now.
=> http: make sure reactor argument is before logger

include/measurement_kit/common/error_or.hpp, test/common/error_or.cpp
This reverts commit 3ab2c8b871749f56fe4f65345b514d9a686c318b because
actually those constructors are used in NDT code.
=> Revert "error_or: remove unused constructors (#630)"

include/measurement_kit/net/transport.hpp, src/ndt/internal.hpp, src/ndt/messages.cpp, src/ndt/messages_impl.hpp, src/ndt/protocol_impl.hpp, src/ndt/test_c2s_impl.hpp, src/ndt/test_meta_impl.hpp, src/ndt/test_s2c_impl.hpp, src/net/transport.cpp, test/ndt/messages.cpp, test/ndt/protocol.cpp, test/ndt/test_c2s.cpp, test/ndt/test_meta.cpp, test/ndt/test_s2c.cpp
Testing on device, I noticed that readn() calling its callback immediately
leads to excessive stack usage and, in the case of receiving Web100 variables
after a NDT test, could exhaust the stack of iOS devices.
Fix this by scheduling a callback for soon even when the buffer already
contains enough data to fullfill the readn() request. Testing on iOS devices
shows that this fix is enough to avoid stack exhaustion and crash.
=> Prevent excessive, O(N) stack consumption

circle.yml
Now that we have set circle-ci up, teach it to run our valgrind-clang
test such that we get a valgrind assessment after each push.
This is super important while developing to make sure that we do
not make mistakes into a feature branch.
- - - 
In parallel with this, I've also promoted the circle-ci check to be
a required check before merging.
So, after this commit is applied, the level of checks we have
for each push is equivalent to before clang stopped working for
us with travis.
=> circle.yml: run valgrind-clang test

src/ooni/dns_injection_impl.hpp, src/ooni/dns_test_impl.hpp, src/ooni/http_invalid_request_line_impl.hpp, src/ooni/ooni_test_impl.hpp, src/ooni/tcp_connect_impl.hpp, src/ooni/tcp_test_impl.hpp, src/ooni/utils.cpp, test/ooni/utils.cpp
1) change lifecycle of `entry` object: rather than keeping it inside
the measurement class, create it before running a test, pass it to
test helper and finally pass it back to be inserted into the keys
of the test into the final entry.
Judging from the documentation on github, this seems quite the
right way of proceedings as reports look much more like what they
oughta be, except for dns-injection for which a real JSON report
is not provided in github but the result feels right.
2) make sure that tests running with no input receive exactly same
treatment of tests with input as regards variables that should
go inside the report (e.g. test runtime)
3) make sure that we use the two digit country names as opposed
to three digit country names, to follow OONI spec
4) remove some unneeded semi …
=> Make sure JSON reports are compliant with spec

.gitignore, include/measurement_kit/common/net_test.hpp, src/common/runner.cpp, test/common/runner.cpp
We can now run the test in many ways and in some of them what is
actually run is not the test but a dynamically allocated copy.
As such, the notion of a unique identifier may lead to surprises
where the same test has two different identifiers; one when is being
scheduled and the other when it is running.
So, better to remove the functionality.
=> net_test.hpp: remove identifier()

.gitignore, include/measurement_kit/ooni/ooni_test.hpp, src/ooni/ooni_test.cpp
Now files are named with the format
"report-{test_name}-{timestamp}-{idx}.json" where idx is an incremental
index that starts from 0 and is increased if a collision is detected.
=> Avoid collisions in naming of ooni test results

include/measurement_kit/common/net_test.hpp, include/measurement_kit/ndt/ndt_test.hpp, include/measurement_kit/ooni/error.hpp, include/measurement_kit/ooni/ooni_test.hpp, src/common/runner.cpp, src/ndt/ndt_test.cpp, src/ooni/ooni_test.cpp, test/ndt/ndt_test.cpp, test/ooni/dns_injection.cpp, test/ooni/http_invalid_request_line.cpp, test/ooni/tcp_connect.cpp
This allows us to pass information about errors to caller to inform it
of errors such as "we cannot open the report file".
=> net_test: now begin() and end() get error param

src/common/utils.cpp, src/common/utils.hpp, test/common/utils.cpp
This copies Neubot's implementation of percentile. I have verified using python3's median() and Google Docs that the numbers in the regress tests are correct.
It would be nice to have a double check on the formula and on the numbers, tho.
This patch will soon be used by NDT code. The idea is to report to the user specific percentile speeds such that it is possible to roughly estimate connection's quality.
=> Copy neubot's implementation of percentile

src/common/logger.cpp
We must guarantee that, if we pass the App a JSON message, this is
actually a valid JSON message.
=> logger: do not fallthrough with invalid JSON message

src/ndt/internal.hpp, src/ndt/ndt_test.cpp
While here, also change the format used to log speed while the test
is in progress to express unit and number in a single entry.
Depends on #725.
=> ndt: write summary at end of test

doc/api/common/logger.md, include/measurement_kit/common/logger.hpp, src/common/logger.cpp, test/common/logger.cpp
This logging is orthogonal from logging specified through the
`on_log()` method such that both can be employed.
Closes #706.
- - - 
While there, also make sure logger's documentation is up to date.
=> Allow logging also on log file

.gitignore, include/measurement_kit/common/net_test.hpp, include/measurement_kit/ooni/ooni_test.hpp, src/ooni/ooni_test.cpp, test/ooni/ooni_test.cpp
While there, fix the name of the default OONI test to be `ooni_test`
rather than being just `net_test`.
Closes #729
=> net_test: add callback to get entry as string

src/ndt/ndt_test.cpp, src/ooni/dns_injection.cpp, src/ooni/http_invalid_request_line.cpp, src/ooni/tcp_connect.cpp, src/ooni/web_connectivity.cpp
For now this patch will do but we'd better properly use copy
construction to avoid losing pieces when we copy.
Also, it would probably make sense to second think the current
approach where we schedule a Var copy of the original object to
see whether there is a better approach for doing the same.
=> Make sure we copy on_entry()

include/measurement_kit/ooni/collector_client.hpp, src/ooni/collector_client.cpp, src/ooni/ooni_test.cpp, test/ooni/collector_client.cpp
As pointed out by @hellais in [#732](https://github.com/measurement-kit/measurement-kit/pull/732#issuecomment-236722618), we should not use the default collector for running end-to-end tests on travis. Fix this by using by default the test collector and by allowing users to override this with a function to get the default collector.
=> By default use testing collector

include/measurement_kit/common/net_test.hpp
Because it should be possible from on_entry() itself to reset it.
=> common/net_test.hpp: on_entry must be a Delegate

build/tarball
It is not included if found in the parent or parent-parent directory, so
run autoreconf -i in a sub-sub-sub folder.
=> build/tarball: make sure install-sh is included

include/measurement_kit/ooni/error.hpp, src/ooni/utils.cpp, src/ooni/utils.hpp, test/ooni/utils.cpp
This PR is related to #738 
I did the following changes:
1. Add a specific error to handle an invalid db. 
2. The constructor will just save the path and nothing more
3. Move the db opening phase to the functions that needs it and leave it open until the destructor is called.
This makes us able to do multiple query to the same db without having to reopen it.
4. Adapt the function `geoip` to return the correct error. I will remove it in future PR  according to #737
I think this will also complete #736 if I interpreted it right.
=> open database just when needed

doc/api/common/settings_entry.md
As experienced by @lorenzoPrimi, this behavior of the Settings
class with respect to booleans is super annoying.
=> settings_entry.md: expand on bug documentation

include/measurement_kit/common/runner.hpp, src/libmeasurement_kit/common/runner.cpp, test/common/runner.cpp
1) make certain possibly ambiguous functions less ambiguous
by adding an underscore to their name.
2) make sure we use Callback rather than std::function.
3) add one more assert.
=> Refactoring of runner

src/libmeasurement_kit/ooni/web_connectivity.cpp
As reported by @lorenzoPrimi in #867, the accessible key was not
correctly set in the output JSON.
This simple diff should fix the issue by setting the accessible
key depending on whether there was blocking.
Closes #867.
=> web_connectivity: set the accessible key

src/libmeasurement_kit/net/connect.cpp, src/libmeasurement_kit/ooni/web_connectivity.cpp
A timeout of at least 30 seconds for connect() should be a reasonable
timeout and it should in particular be more reasonable than five seconds
given that we have seen that inactive heroku machines, for example,
take more than five seconds to respond.
This should fix the immediate bug reported in #864. I've yet to decide
whether this would also mean we can close the bug or not.
=> connect.cpp: increase default net/timeout

src/libmeasurement_kit/ooni/ooni_test.cpp
While checking the output of NDT with @bassosimone we discovered this bug, where the JSON doesn't have a valid type entry.
=> Bug in ndt JSON

src/libmeasurement_kit/http/request.cpp
If the user has not asked to follow redirect (i.e. the max number of
redirects is zero or less than that), do not enter into the branch
where we follow the redirect even if there is a `location` header in
the received headers set.
Fix originally implemented to #811 and backported as hotfix.
=> http/request: don't redirect if *max_request <= 0

src/libmeasurement_kit/libevent/dns_impl.hpp
We noticed using MK on Android that some logs were not on the correct logger!
A solution that I found to pass the logger to the libevent callback was to put the logger inside the context structure that we pass to evdns_resolver_*
=> Log dns debug to the correct logger

src/libmeasurement_kit/net/connect.cpp, src/libmeasurement_kit/net/connect_impl.hpp, src/libmeasurement_kit/net/listen.hpp
Quoting from the diff itself:
```diff
+    /*
+     *  Rationale for deferring callbacks:
+     *
+     *  When using IOCP on Windows, the kernel calls callbacks when selected
+     *  events occur (i.e., there is no loop that guarantees callbacks run in
+     *  the same thread); set DEFER_CALLBACKS to tell libevent to serialize
+     *  bufferevent's callbacks into the event loop to avoid creating MT issues
+     *  in code that otherwise (on Unices) is single threaded.
+     *
+     *  Yes, the current implementation forces serializing the callbacks also
+     *  on Unix where this wouldn't be needed thus adding some overhead. For
+     *  uniformity, I am for serializing for all platforms and then, if we see
+     *  that there's too much overhead, to only enable that on Windows.
+ …
```
=> bufferevent: use BEV_OPT_DEFER_CALLBACKS

src/libmeasurement_kit/ooni/ooni_reporter.cpp
We cannot fix the report written on disk, however, because that
would break the API and I would defer that to v0.4.0.
=> ooni_reporter.cpp: make sure we submit report id

include/measurement_kit/ndt/run.hpp, src/libmeasurement_kit/ndt/internal.hpp, src/libmeasurement_kit/ndt/ndt_test.cpp, src/libmeasurement_kit/ndt/run.cpp, src/libmeasurement_kit/ndt/run_impl.hpp, test/ndt/run.cpp
While there, remove one XXX by moving defines in the public header
and using the real-ndt-names only inside of private sources.
Closes #844
=> ndt: exchange reactor and logger arguments

include/measurement_kit/common/reactor.hpp
Spotted while doing random things for which I needed to include `reactor.hpp` directly.
=> reactor.hpp: add missing header

include/measurement_kit/ndt/ndt_test.hpp, include/measurement_kit/ndt/run.hpp, include/measurement_kit/ooni/collector_client.hpp, include/measurement_kit/ooni/dns_injection.hpp, include/measurement_kit/ooni/http_invalid_request_line.hpp, include/measurement_kit/ooni/ooni_reporter.hpp, include/measurement_kit/ooni/ooni_test.hpp, include/measurement_kit/ooni/tcp_connect.hpp, include/measurement_kit/ooni/templates.hpp, include/measurement_kit/ooni/web_connectivity.hpp, src/libmeasurement_kit/ooni/ooni_reporter.cpp, src/libmeasurement_kit/ooni/ooni_test.cpp
Ideally, I'd like to always use namespaces rather than taking
shortcuts using `using namespace`. One step at a time.
=> Do not use `using namespace` in public headers

doc/api/common/logger.md, include/measurement_kit/common/logger.hpp, include/measurement_kit/nettests/base_test.hpp, src/libmeasurement_kit/common/logger.cpp, src/libmeasurement_kit/nettests/base_test.cpp, test/common/logger.cpp
For now, if such callback is not set, pass through events to the log
callback for backward compatibility with MK v0.3.x.
Closes #923.
=> logger: add callback for JSON encoded events

doc/api/common/logger.md, include/measurement_kit/common/logger.hpp, include/measurement_kit/nettests/base_test.hpp, src/libmeasurement_kit/common/logger.cpp, src/libmeasurement_kit/ndt/internal.hpp, src/libmeasurement_kit/ndt/protocol_impl.hpp, src/libmeasurement_kit/ndt/run_impl.hpp, src/libmeasurement_kit/nettests/base_test.cpp, src/libmeasurement_kit/nettests/runnable.cpp, src/measurement_kit/cmdline/ndt.cpp
I implemented this adding to `Logger` and `BaseTest` convenience
features allowing to easily pass around test progress.
Closes #922
=> ndt: print progress of the test

src/libmeasurement_kit/ndt/run_impl.hpp, src/measurement_kit/cmdline/ndt.cpp
Allows to connect to neubot's botticelli servers easily.
Closes #921.
=> ndt: allow to specify alternative mlabns tool

src/libmeasurement_kit/dns/system_resolver.hpp
Honestly, those are not super important flags anyway, because they
instruct getaddrinfo to return ipv4-mapped addresses only when there
are no IPv6 addresses and one requests for AAAA.
We always request for both A and AAAA when we resolve for connecting (and
for more precise results one should probably use c-ares in future).
Sure, I could keep the feature, but then I wonder whether this would lead
to the library behavior being inconsistent across different platforms in
a not-super-simple-to-debug way.
For this reason, I'm removing the feature entirely rather than just
making it conditional on !__ANDROID__.
=> getaddrinfo: android dislikes AI_V4MAPPED | AI_ALL

doc/api/nettests/base_test.md, include/measurement_kit/nettests/base_test.hpp, include/measurement_kit/nettests/runnable.hpp, src/libmeasurement_kit/nettests/base_test.cpp, src/libmeasurement_kit/nettests/runnable.cpp, test/nettests/runnable.cpp
Useful to free resources allocated in the Java code. As some other
callbacks, this one can be set multiple times. We should probably
find another convention, rather than on_foo(), for callbacks settable
more than once, to make it more intuitive.
=> runnable: add on_destroy() callback

src/libmeasurement_kit/dns/query.cpp
It should have been done in #972 but something went wrong during
the pull request process and we only created the condtions for that
to work correctly (I suspect some rebase went wrong).
=> By default use the system-resolver

src/libmeasurement_kit/dns/system_resolver.hpp
This is too low level. For example, we can get an error here
because we're resolving AAAA and there is no associated record
but in fact there is a record for A and we can connect.
Issue noticed on measurement-kit/ios-example where this is the
last log message printed during each working test.
The general principle is that low level code should not warn or
emit log messages for failure unless it's unrecoverable.
=> system_resolver.hpp: do not warn on getaddrinfo failure

ChangeLog.md, configure.ac, doc/api/common/version.md, doc/index.md, include/measurement_kit/common/version.h, measurement_kit.podspec
Integration branch for release v0.4.0-beta. It will be merge-squashed into `stable` once all the following pull requests have been tested and merged into `stable`.
=> Release: v0.4.0-beta

.travis.yml, build/docker/script/run, build/docker/script/setup, build/docker/spec/coveralls, build/travis, test/net/ssl_context.cpp
This pull request firstly exposes that coveralls was not working (see [travis job #4426.1](https://travis-ci.org/measurement-kit/measurement-kit/jobs/191907943)) and that `.travis.yml` was not serving us well because it would have been much better for the build to fail if coverage could not be submitted.
Hence:
1. move verbatim the script part of `.travis.yml` to `./build/travis` and make sure the script fails when it needs to fail (as evidenced by the afore-mentioned build that now fails as it ough to be)
2. solve the issue that coveralls is not working by admitting that I am now pissed off of using ubuntu 12.04 and that I would be much better off using ubuntu 16.10 through docker
Changes in here mostly backported from #1035. It is safe to move forward and merge this pull request as an …
=> travis: fix coveralls

.gitlab-ci.yml, .travis.yml, build/dependency, build/docker/script/run, build/docker/script/setup, build/docker/spec/coveralls, build/docker/spec/valgrind-clang, build/docker/spec/valgrind-gcc, build/spec/embedded-mk, build/spec/mk, circle.yml
Rather than duplicating code to build a package, tap into the
`./build/dependency` script.
Move code to install required dependencies in the `run` script
of `./build/docker/script`, to reduce specs complexity.
=> Finish cleaning up docker build system

build/ios/build-frameworks
On my system I have a case sensitive drive, this means that iphoneos !=
iPhoneOS.
It appears that the built iOS dependencies end up inside of a directory
called "iphoneos" and "iphonesimulator", leading to the cp comands to
fail when the drive is case sensitive, but succeeding when they are case
insensitive (as is the case with most OSX installs).
=> Attempt to fix issue with case sensitive drive (#1076)

doc/api/ooni/utils.md, include/measurement_kit/ooni/utils.hpp, src/libmeasurement_kit/ooni/templates.cpp, src/libmeasurement_kit/ooni/utils.cpp, test/ooni/utils.cpp
Closes #1065. Specifically:
1) change name from represent_http_body to represent_string since
the function is now used more generally than for the body
2) use represent_string to also represent the response line and the
value of headers that both could be non UTF-8
There is no need to represent the name of the headers because
the standard says that it's
>
>    header-field   = field-name ":" OWS field-value OWS
>    field-name     = token
>
>    token = 1*tchar
>
>    tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*"
>                / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
>                / DIGIT / ALPHA
>                ; any VCHAR, except delimiters
>
>    ALPHA =  %x41-5A / %x61-7A   ; A-Z / a-z
>    DIGIT =  "0" / "1" / "2" / "3" / "4" / "5" / "6" /
>                   "7" / …
=> Make sure http template produces good json

doc/api/common/var.md, include/measurement_kit/common/error.hpp, include/measurement_kit/common/var.hpp, include/measurement_kit/net/connect.hpp, src/libmeasurement_kit/common/error.cpp, src/libmeasurement_kit/net/connect.cpp, test/common/var.cpp
When developing a diff to improve NDT, I mistakenly wrote:
```C++
ErrorOr<std::vector<double>> ctimes = net::get_connect_times(err);
```
instead of:
```C++
ErrorOr<double> ctime = net::get_connect_time(err);
```
after `connect()`. Now, both functions internally use Var<T>::as()
to cast from a generic `ErrorContext` to a specific context.
The net effect of calling `get_connect_times` rather than the more
humble `get_connect_time` is that `ErrorContext` is downcasted to
`ConnectManyResult` rather than to `ConnectResult`. Since the cast
is not possible, one would have expected the cast to fail and the
resulting Var<T> to hold a nullptr. Hence the `ErrorOr` should not
be a value but rather an error. Right?
Wrong! What I obtained instead was a segfault.
It turns out that using a static-pointer …
=> var.hpp: fix as() to use dynamic cast

build/valgrind/openssl.supp, test/net/connect.cpp
This way, a test failing does not cause the failure of all the
following tests and we can see easily what has failed.
Related to #919
=> test/net/connect.cpp: refactor to avoid global poller

doc/api/net/connect.md, src/libmeasurement_kit/net/connect_impl.hpp
* connect_impl: fix treatment of IPv6 addresses
I believe, this diff alone should be enough to fix the issue
reported in measurement-kit/ooniprobe-ios#61.
I have noticed that also from my home (where there is no IPv6
connectivity) the code fails because it cannot even parse such
addresses. With this diff applied, instead, it fails because
of a `host_unreachable` error, which makes more sense to me (of
course, to see the real error, all of #1098 is required).
* connect: document scoped link-local IPv6 addrs bug
I was temped to fix this as part of this pull request but then
noticed it would have taken a bit of refactoring that instead I
would like to perform separately.
* connect: add warnings for each error case
We can (and will) do better by mapping errors, but, for now, let's
start by …
=> connect: start fixing IPv6 addresses

include/measurement_kit/net/error.hpp, src/libmeasurement_kit/libevent/connection.cpp, src/libmeasurement_kit/net/connect.cpp, src/libmeasurement_kit/net/connect_impl.hpp, src/libmeasurement_kit/net/utils.cpp, src/libmeasurement_kit/net/utils.hpp, test/net/utils.cpp
Extracted from #1098. Adds enough verbosity to understand from the logs what is going on, but avoids changing the behaviour or changing (or refactoring) the code.
=> net: start exposing network errors

doc/api/ooni/collector_client.md, include/measurement_kit/ooni/collector_client.hpp, src/libmeasurement_kit/ooni/web_connectivity.cpp, src/libmeasurement_kit/report/ooni_reporter.cpp, src/measurement_kit/cmdline/web_connectivity.cpp, test/nettests/dns_injection.cpp, test/nettests/http_invalid_request_line.cpp, test/nettests/multi_ndt.cpp, test/nettests/ndt.cpp, test/nettests/runnable.cpp, test/nettests/runner.cpp, test/nettests/tcp_connect.cpp, test/nettests/utils.hpp, test/nettests/web_connectivity.cpp
Basically always except in the regress tests. Refactor regress tests
a bit to make sure it is not an hell to keep them up to date.
=> Use default backends when it makes sense

include/measurement_kit/net/error.hpp, src/libmeasurement_kit/http/request.cpp, src/measurement_kit/cmdline/http_request.cpp, test/http/request.cpp
We had logic to specially deal with EOF to signal end-of-body, however
the code was not resetting error after EOF resulting in inability to
process redirects where bodies were terminated by EOF.
This causes measurement-kit/ooniprobe-ios#79 reported by @willscott.
For the records, I also saw a failure for `hushmail.com` but I flagged
it as a transient network error. However, when also @willscott reported
the same error, it was clear this was something more than I thought.
While there, give a meaningful name to error 1000.
Also, since there is an open pull request refactoring HTTP, and
specifically I refer to measurement-kit/measurement-kit#1041, it
is wise to make sure this error is not re-introduced there.
=> http: fix EOF-implies-end-of-body logic

build/valgrind/openssl.supp, doc/api/net/utils.md, include/measurement_kit/net/utils.hpp, src/libmeasurement_kit/net/connect_impl.hpp, src/libmeasurement_kit/net/utils.cpp, test/net/connect.cpp, test/net/utils.cpp
Run log on a box where `nc -vl fe80::1%lo0 8080`:
```
$ ./measurement_kit net_connect -vvp 8080 fe80::1%lo0
[D] resolve_hostname: fe80::1%lo0
[D] resolve_hostname: is valid ipv6
[D] connect_first_of begin
[D] connect_base [fe80::1%lo0]:8080
[D] connect() in progress...
[D] connect time: 0.000344
[D] connect_first_of success
```
=> connect: support also ipv6 link local with scope

.gitlab-ci.yml
We have seen that the Valgrind that ships with xenial produces too
many errors with measurement_kit, so use yakkety instead.
=> Fix gitlab on stable by using yakkety

configure.ac, doc/api/net/transport.md, example/libevent/discard.cpp, example/libevent/listen.cpp, include/measurement_kit/net/transport.hpp, src/libmeasurement_kit/libevent/connection.cpp, src/libmeasurement_kit/libevent/connection.hpp, src/libmeasurement_kit/net/connect.cpp, src/libmeasurement_kit/net/emitter.cpp, src/libmeasurement_kit/net/emitter.hpp, src/libmeasurement_kit/net/socks5.cpp, src/libmeasurement_kit/net/socks5.hpp, src/libmeasurement_kit/net/transport.cpp, test/ndt/protocol.cpp, test/ndt/test_meta.cpp, test/net/connect.cpp, test/net/emitter.cpp, test/ooni/collector_client.cpp
- Use a number of interfaces to clearly indicate what are the
different functionality that a Transport must implement
- Specify more clearly the interface between the generic network
code and the specific libevent (for now) code
- Distinguish between the base skeleton of an Emitter and the
actual Emitter class sometimes used for testing
=> Make Transport more OO

doc/api/net/transport.md, include/measurement_kit/net/transport.hpp, src/libmeasurement_kit/libevent/connection.cpp, src/libmeasurement_kit/libevent/connection.hpp, src/libmeasurement_kit/net/emitter.cpp, src/libmeasurement_kit/net/emitter.hpp, src/libmeasurement_kit/net/socks5.hpp
This refactoring makes the whole close logic model more consistent
and in particular it ensures that, after close, we do not emit events,
which will help to refactor socks5 as a factory.
While doing that, update documentation and especially make sure
we list limitations of the current model under BUGS.
=> net: move most close logic in emitter

src/libmeasurement_kit/http/request.cpp, src/libmeasurement_kit/ooni/templates.cpp, test/net/connect.cpp, test/ooni/templates.cpp
- make sure we include all requests and responses in OONI templates
so that we see redirections in the results
- reduce the number of cases where issueing an HTTP request has
as result an error coupled with a `nullptr` response
- fix regress to be compatible with both libevent 2.0 and 2.1
Closes #1143.
=> ooni/templates http: include all request/responses

build/valgrind/openssl.supp, doc/api/net/connect.md, src/libmeasurement_kit/net/connect.cpp, src/libmeasurement_kit/net/ssl_context_impl.hpp
1. it turns out the new code to map to errno returned ValueError when
errno was equal to zero, which happens in the connect() path in case
of SSL error, however the code receiving the error code expected to
receive NetworkError
2. we were using TLSv1 as method, under the expectation that it covers
all above TLSv1, which is wrong; SSLv23 should be used instead, coupled
with disabling SSLv2 and SSLv3 that are deprecated (actually SSLv2 is
disabled by default but I wanted to be very explicit in new code)
=> Fix "unknown_failure 3" bug

include/measurement_kit/http/http.hpp
Previously, numbers need not to be initialized because we were returning
a response only when we successfully received one.
However, recently we started returning non-nullptr responses also on error,
providing how much information as we could.
Still, some assumptions that held before are not true after that change.
So, for example, as we've seen [in a recently failed travis-ci build](
https://travis-ci.org/measurement-kit/measurement-kit/jobs/210072026#L1980),
having http::Response numeric fields not initialized can lead to
undefined behavior, as reported by lovely Valgrind.
The fix is as simple as setting these fields to a known value.
Another question, however, would be how come that we have fields that
are not initialized but no error has been reported by parser.
That is quite simple …
=> http::Response: init numbers to know value

src/libmeasurement_kit/common/utils.cpp, test/common/utils.cpp
My eyes are still bleeding after I noticed what I did initially
commit to find end of string, not to mention how I did fail to
provide a solid regress case for catching that.
=> Fix embarassing mk::endswith() bug

src/libmeasurement_kit/http/request.cpp, test/http/request.cpp
To this end, we need to add code for the case where the redirection is
towards a relative, rather than absolute, path.
As said in a comment, I thought this should not happen, but we've seen
cases in the wild where it does, so here we are with a patch.
While there, make use of mk::startswith() and mk::endswith() for
additional clarity.
=> Fix unknown_error_3009 bug

include/measurement_kit/report/entry.hpp, src/libmeasurement_kit/report/entry.cpp
This diff, which costed me more fatigue than it seems, stops using
the constructor of `nlohmann::json` for implementing `report::Entry`,
because of the following reasons:
1. the latest version of the NDK fails to build `report::Entry`
with this interestingly not-so-clear error:
> In file included from .../include/measurement_kit/report/report.hpp:8:
> .../include/measurement_kit/report/entry.hpp:16:27: error: recursive
>     evaluation of default argument
>   using nlohmann::json::json;
2. upgrading to the latest version (2.1.1) of nlohmann::json breaks
`report::Entry` build in several places
Instead, with this diff applied (and with further small tweaks for 2.1.1),
I have seen both NDK and with-v2.1.1 builds terminating, including at
least a build using Valgrind:
> …
=> Fix report/entry.hpp w/ new NDK, nlohmann::json

build/docker/spec/coveralls
Otherwise the catch is that opening pull requests from non team
members will always fail the build because of missing token.
See during #1141.
=> Only run coveralls if we know the token

doc/api/report/file_reporter.md, src/libmeasurement_kit/report/file_reporter.cpp
Closes #866.
I have decided not to go fancy and always check for filename
being equal to "-" because there was no need to be more complex
than that: the function to write the entry is called once for
every test, and this event does not occur very frequently.
=> Allow writing report on the stdout

.gitignore, ChangeLog.md, NOTICE, doc/api/common/mock.md, include/measurement_kit/common/mock.hpp, src/libmeasurement_kit/common/utils_impl.hpp, src/libmeasurement_kit/http/request_impl.hpp, src/libmeasurement_kit/mlabns/mlabns_impl.hpp, src/libmeasurement_kit/ndt/messages_impl.hpp, src/libmeasurement_kit/ndt/protocol_impl.hpp, src/libmeasurement_kit/ndt/run_impl.hpp, src/libmeasurement_kit/ndt/test_c2s_impl.hpp, src/libmeasurement_kit/ndt/test_meta_impl.hpp, src/libmeasurement_kit/ndt/test_s2c_impl.hpp, src/libmeasurement_kit/net/connect_impl.hpp, src/libmeasurement_kit/ooni/collector_client_impl.hpp, src/libmeasurement_kit/ooni/resources_impl.hpp, src/libmeasurement_kit/ooni/utils_impl.hpp
Basically:
- MK_MOCK() simplification
- Add `node_modules` to `.gitignore`
- Add NOTICE file
- Sync up the ChangeLog.md file
=> Backports from master: MK_MOCK() + small changes

build/ios/library, build/spec/mk
The `embedded-mk` spec has long gone.
=> Build using the `mk` spec

configure.ac
configure.ac: force non-strict http-parser (#1225)
This should fix web_connectivity of `mail.voila.fr`.
See #1196.
=> Backport #1225 from master

src/libmeasurement_kit/ext/http_parser.c, test/http/response_parser.cpp
Fixes advertising possible protocol upgrade to, e.g., `http2`
such as the case noticed with `http://www.aseansec.org`.
=> Cherry pick nodejs/http-parser#364

doc/api/common/async_runner.md, doc/api/nettests/runner.md, include/measurement_kit/common/async_runner.hpp, include/measurement_kit/common/has_global_factory.hpp, include/measurement_kit/nettests/runner.hpp, src/libmeasurement_kit/nettests/runner.cpp, test/nettests/runner.cpp
Extract a generic runner from the existing nettests::Runner
implementation and move it into the common module.
=> Further refine the runner model

src/libmeasurement_kit/ooni/orchestrate.cpp
I also sorted alphabetically to ease the task of checking whether
all the meaningful variables inside the `ClientMetadata` class are
serialized. Will do a double check before merging.
Bug spotted by @hellais.
=> orchestrate.cpp: serialize also language

include/measurement_kit/common/reactor.hpp, include/private/dns/getaddrinfo_async.hpp, include/private/dns/system_resolver.hpp, include/private/libevent/poller.hpp
Better that all the classes that mess with objects have the
same lifecycle. One way to do that is to put the worker into
the reactor, so bydef they have the same lifecycle.
=> feature: use newly added reactor's worker

test/common/worker.cpp
Now concurrency is unsigned, so checking for it being greater
or equal than zero is clearly redundant.
=> fix(t/c/worker.cpp): silence compiler warning

.gitignore, include/private/libevent/reactor.hpp, src/libmeasurement_kit/common/reactor.cpp, test/libevent/reactor.cpp
Use less confusing name. That class implements reactor, so
call it reactor in the mk::libevent namespace.
=> rename(libevent): poller -> reactor

test/nettests/runnable.cpp, test/nettests/utils.hpp
1. in `test/nettests/runnable.cpp` avoid the races that were so
annoying when I was finishing #1297 up
2. in `test/nettests/utils.hpp` avoid doing collect for tests for
which we really do not care about doing any collect
=> fix(test/nettests): avoid races and optimize duration

.travis.yml
At least on the CI environment, I would like the code not to
produce any warning. In other scenarios, there _may_ be a few
warnings caused by porting software. For example, I do see
a few warnings about chars that cannot be negative on Android
on platforms that are negative. The code triggering such
warnings is not from us but from third parties.
=> .travis.yml: add -Werror to CXXFLAGS and CFLAGS

.travis.yml, build/docker/script/setup, build/docker/spec/valgrind-clang
Based on #1316. The rationale for having `-Werror` for C++ only is that we _only_ write C++ code and the C code we have in tree is from third parties. As such, I guess it's okay to require that only our code does not produce any warning only. `-Werror` for C is disabled because [configure fails with -Werror and GCC]( https://travis-ci.org/measurement-kit/measurement-kit/jobs/270364007 ).
Closes #1317
=> travis: make sure we honour -Werror for C++

build/fetch-dep, build/ios/library, build/sign, build/tarball, doc/tutorial/unix.md
It seems now `gpg2` is simply shipped as `gpg`.
=> fix(*): use `gpg` rather than `gpg2`

build/ios/cross, include/private/ooni/utils.hpp, measurement_kit.podspec, src/libmeasurement_kit/nettests/runnable.cpp, src/libmeasurement_kit/ooni/utils.cpp, src/libmeasurement_kit/ooni/web_connectivity.cpp, test/ooni/utils.cpp
This was initially submitted as #1314. Then it was reverted in #1321, because iOS does not support `thread_local` (#1319).
However, [research](https://stackoverflow.com/a/29929949) suggests that it is actually supported for iOS >= 9.0.
As of today, the market share of iOS >= 9.0 is 98.58% (data gathered from [apteligent](https://data.apteligent.com/ios/) and subject to change in the future, of course).
It seems to me it makes a lot of sense to remove support for iOS < 9 and have the `thread_local` feature. If we _really_ need iOS 8 support, I can write some iOS 8 specific code using pthreads.
I really prefer a solution based on `thread_local` storage rather than one with a global cache for which we should maintain locking and for which we should have destruction from possibly multiple …
=> fix(geoip): make cache thread local

.gitignore, autogen.sh, build/autogen.d/geoip, test/ooni/utils.cpp
This file is huge and unused by OONI or by anyone else. We fetch
it every time we compile. And this is a waste.
=> fix(geoip): remove all refs to GeoLiteCity

include/private/libevent/reactor.hpp, test/libevent/reactor.cpp
Do not relay on side effect of a constructor of an unused
object to initialize libevent once.
Rather, have explicit initialization function.
The paranoia here is that a compiler may optimize away
initialization because the compiler sees that the object
is actually unused.
Use a proper initialization function, instead.
=> fix(libevent): better initialize once code

acinclude.m4, build/ios/cross, include/private/net/libssl.hpp
- fix(i/p/n/libssl.hpp): include default CA bundle
- fix(acinclude.m4): default CA bundle when cross compiling
- feature(build/ios/cross): make build quiet
=> fix: ios build

.clang-format
It is very annoying that functions are not aligned to 4 spaces
because of the continuation indent.
=> [ci skip] fix(.clang-format): set continuation indent to zero

ChangeLog.md, build/ios/archive-library, build/ios/library, build/spec/mk, configure.ac, doc/api/common/version.md, doc/index.md, include/measurement_kit/common/version.h, measurement_kit.podspec, src/libmeasurement_kit/ooni/templates.cpp, test/ooni/templates.cpp
This fix should _also_ be backported to the integration branch for
`v0.8.0` and to the stable branch, cutting `v0.7.3`.
Note: this is a cherry-pick of aaf1781b18a99c440da1c65d5a71ebf86e3a4321
from master that has been backported to stable.
Conflicts:
src/libmeasurement_kit/ooni/templates.cpp
test/ooni/templates.cpp
=> Release v0.7.3

test/http/request.cpp, test/ooni/templates.cpp
It seems Politecnico di Torino has now applied some filter
that prevents our regress tests from fetching a PDF.
Repair by using other URLs.
=> Repair failing regress tests

src/libmeasurement_kit/ooni/collector_client.cpp, test/ooni/collector_client.cpp
Closes TheTorProject/ooniprobe-ios#131
This needs to be backported in v0.8.x and v0.7.x.
=> fix(collector_client): recognize build number

src/libmeasurement_kit/common/logger.cpp
Use `std::endl` rather than `\n` when emitting logs. Force flushing logs at end of test and fixes TheTorProject/ooniprobe-ios#80.
This is the forward port of the fix tested for `v0.7.4` to `master`.
Cc: @hellais
=> fix(logger): force ofile flush for each entry

build/ios/cross, include/private/net/libssl.hpp, src/libmeasurement_kit/net/connect.cpp, src/libmeasurement_kit/ooni/utils.cpp, test/net/libssl.cpp
[Cherry-pick of #1402 from `stable`.]
There is empirical evidence that MK v0.7.5 crashes on 32 bit iOS systems
because thread_local isn't working properly.
See #1397.
This diff is an attempt to fix the issue in a very light way. Basically,
retain the thread local semantic, but allocate a cache very time if
thread_local is known to misbehave.
This fix makes the code less efficient for those devices where thread_local
is not working, of course. In fact, basically, for those devices any kind of
caching is disabled.
Yet, given that this seems to affect a minority of our users, I've decided
to go for an as-simple-as-possible fix that prevents the crash.
(Also, `armv7` and `armv7s` are going to disappear anyway in the near future,
because Apple is now mostly focusing on `arm64`.)
While there …
=> Fix for systems that don't support thread_local

build/docker/spec/valgrind-clang, build/docker/spec/valgrind-gcc
For continuous integration, let's use flags more similar to the ones used by Debian.
=> travis: improve build flags

include/measurement_kit/common/reactor.hpp, include/private/common/libevent_reactor.hpp, include/private/common/worker.hpp, include/private/dns/getaddrinfo_async.hpp, src/libmeasurement_kit/common/worker.cpp, src/libmeasurement_kit/nettests/base_test.cpp, src/libmeasurement_kit/ooni/orchestrate.cpp, test/common/worker.cpp
<strike>Depends on #1446.</strike>
Closes #1387.
Required for v0.8.0-beta.
=> reactor: correctly deal with exception in child thread

include/measurement_kit/nettests/nettests.hpp, src/libmeasurement_kit/nettests/base_test.cpp
- make sure we move in all callbacks
- use std::function and not mk::Callback (more standard components
hence less cognitive overhead)
- reorder the methods a bit
- trim includes
=> nettests: prepare for API v1.0.0

.gitignore, include/measurement_kit/common/raw_ptr.hpp, include/private/common/libevent_reactor.hpp, test/common/libevent_reactor.cpp, test/common/raw_ptr.cpp
Makes the management of the lifecycle of raw C pointers much
more structured than it's currently.
The plan is to use it to make more easy and yet robust to
change the underlying bufferevent used by Transport.
=> feature(raw_ptr): smart pointer for raw C pointers

include/measurement_kit/common/unique_ptr.hpp, include/private/common/libevent_reactor.hpp, test/common/unique_ptr.cpp
After reading excerpts of book on C++ recommended by @hellais, I did
convince myself that it's better not to implicitly cast a smart pointer
to its underlying pointer type, but it's better to have an explicit
method, as `get()` for doing that.
After this change, RawPtr now really looks like a wrapper for a unique
pointer, hence just rename it for clarity and propagate changes.
=> Rename raw_ptr as unique_ptr

.gitignore, include/private/common/libevent_reactor.hpp, include/private/common/worker.hpp, src/libmeasurement_kit/common/worker.cpp
Closes #1434.
While there, make the reactor less noisy when it exits.
=> worker: use parallelism 1 in default queue

include/private/dns/getaddrinfo_async.hpp
Spotted when building for Android.
=> fix(getaddrinfo_async.hpp)'s compiler warning

include/private/dns/getaddrinfo_async.hpp
Spotted when building for Android.
=> fix(getaddrinfo_async.hpp)'s compiler warning (#1481)

include/measurement_kit/common/aaa_base.h, include/measurement_kit/common/logger.hpp, include/measurement_kit/common/socket.hpp, include/private/dns/utils.hpp, include/private/ext/tls_internal.h, include/private/libevent/connection.hpp, src/libmeasurement_kit/common/citrus_utf8.c, src/libmeasurement_kit/common/logger.cpp, src/libmeasurement_kit/ext/tls_verify.c, src/libmeasurement_kit/ooni/whatsapp.cpp, src/libmeasurement_kit/portable/strtonum.c
Avoids importing specific portable headers manually.
Allows for further simplifications.
Will deal with the ciso646 fallback on Windows.
=> fix(aaa_base): make it a C header

Vagrantfile
The current Vagrantfile uses yakkety, but trying to pull the image gives a 404. This PR replaces yakkety with zesty, which does not 404.
=> Update Vagrantfile to use zesty instead of yakkety

include/measurement_kit/common/error.hpp, src/libmeasurement_kit/ndt/messages_impl.hpp, src/libmeasurement_kit/ndt/protocol_impl.hpp, src/libmeasurement_kit/ndt/run_impl.hpp, src/libmeasurement_kit/ndt/test_c2s_impl.hpp, src/libmeasurement_kit/ndt/test_meta_impl.hpp, src/libmeasurement_kit/ndt/test_s2c_impl.hpp, src/libmeasurement_kit/net/connect.cpp, src/libmeasurement_kit/nettests/multi_ndt.cpp, test/common/error.cpp
This diff introduces a set of non-breaking correctness-related
changes to the Error class:
- explicit single-argument constructor
- enforce move semantic when adding child errors
Extracted from #1531. This should not be controversial and we can
perhaps see to merge it while deciding how to further refactor the
Error class according to the discussion in #1531.
=> refactor(error): explicit ctor, move semantic

include/measurement_kit/mlabns/mlabns.hpp, include/private/mlabns/mlabns_impl.hpp, src/measurement_kit/cmd/ndt.cpp
This PR backports the changes to master that implement the `-C` flag to the ndt subcommand, which allows for querying the mlab_ns system by country.
=> Backport country flag into stable branch

include/measurement_kit/dns/error.hpp, include/measurement_kit/net/buffer.hpp, src/libmeasurement_kit/common/utils.cpp, src/libmeasurement_kit/dns/getaddrinfo_async.hpp, test/common/utils.cpp, test/dns/system_resolver.cpp
This diff reduces the places where we throw `Error` below `include`. This is part of the work required to decouple `Error` and `std::exception`, as discussed with @pboothe in #1531.
=> include: reduce places where we throw Error

include/measurement_kit/nettests/nettests.hpp, src/libmeasurement_kit/nettests/base_test.cpp
1. I deprecated and then removed this API to clean up
2. but actually this was used by JNI bindings
3. so, readd it
4. do not bother with deprecation because it only creates
more annoyances when compiling Java bindings
=> fix(nettests.hpp): repair JNI bindings

build/android/dependency, build/ios/dependency
In master we've agreed to reduce the number of architectures
for which we cross compile for Android and iOS.
Follow suit on stable. This can go in without explicit ACKs by
anyone since it's something we already agreed for.
=> build: sync built archs with master

script/build/c-ares, script/build/geoip, script/build/libevent, script/build/libressl, script/build/mk
Put everything into the same directory. This is what existing script except. Rather than patching them to support a new style, better to use the previously existing convention.
=> Make cross building much simpler

test/mlabns/mlabns.cpp, test/ooni/templates.cpp
Two tests had this assumption. It's bogus. Especially from my house
where I have Vodafone that always replies to DNS.
Having some tests failing when I run tests locally is so bad.
Fix these instances by setting an unreasonable timeout so that we
basically verify that we deal with the failure.
(Rather than failing because we receive no reply with an invalid
DNS server, now we fail for the super-low timeout.)
=> Fix tests assuming an invalid DNS server would never reply

src/libmeasurement_kit/nettests/runnable.cpp, src/libmeasurement_kit/ooni/utils.cpp
Unclear what the real cause is. The failure seems to be related
with relying on exceptions to report the Error.
(I tried to define a virtual destructor for Error and all the
derived class, but that did not help.)
Cherry-picked from #1535
=> Fix GeoIP crash with missing DB on Windows

acinclude.m4, configure.ac
With these fixes committed, the code works with the cross toolchain
having C++11 support that I recently compiled for macOS.
=> acinclude.m4 configure.ac: fixes to compile with mingw-w64-cxx11

build/spec/Catch, script/vendor/catch, src/libmeasurement_kit/ext/catch.hpp
The goal of this diff is two-fold: (1) update to the latest
release of catch in the v1.x branch, (2) remove one more user
of the `./build/dependency` legacy script.
=> Update catch to v1.12.2 and the related vendor script

.ci/docker/cmake, test/nettests/utils.hpp
While there, be prepared for using the production infrastructure for CI, by adding specific annotations to CI-run tests. (See below.)
cc: @hellais 
Closes #1307. Specifically, rather than using the testing infrastructure, this PR adds an annotation to tests run using the production infrastructure. This, as mentioned above, is in preparation of using the whole production infrastructure, but currently this PR also points to the collector to the new collector implementation, which is currently not production.
=> test/nettests: use new collector implementation

src/libmeasurement_kit/nettests/runnable.cpp
Closes #1435 
```JSON
{
"annotations": {
"engine_name": "libmeasurement_kit",
"engine_version": "0.9.0-beta",
"engine_version_full": "v0.9.0-beta",
"failure_asn_lookup": "true",
"failure_network_name_lookup": "true",
"platform": "macos"
}
}
```
=> Add annotations when geoip-lookup steps fail

src/libmeasurement_kit/ooni/http_invalid_request_line.cpp
This closes: https://github.com/measurement-kit/measurement-kit/issues/1679
=> Fix off-by-one with http_invalid_request_line test

src/libmeasurement_kit/common/encoding.cpp, src/libmeasurement_kit/common/encoding.hpp, src/libmeasurement_kit/http/request.cpp, src/libmeasurement_kit/ooni/web_connectivity.cpp
We recently enabled LOG_DEBUG2 when running OONI mobile in debug
mode. However, we also recently changed the code to emit logs using
the JSON format. As a consequence, we need to properly quote the
emitted body, when it is not UTF-8, otherwise the JSON library will
crash when trying to serialise the log event.
FWIW, the new HTTP code (https://github.com/measurement-kit/mkcurl)
has an API that explicitly forces you to reason about the body being
possibly binary. When we wrote the code that currently is inside of
MK, we did not consider this risk of logging a binary body because we
were just writing strings on a C++ stream. When we switched to a model
where log events were JSON, we did not consider this issue.
Closes #1699.
=> fix logging: make sure we base64 non-UTF-8 bodies

src/libmeasurement_kit/nettests/runnable.cpp, src/libmeasurement_kit/nettests/runnable.hpp, src/libmeasurement_kit/nettests/web_connectivity.cpp
Today, I discussed this issue further with @lorenzoPrimi and it
seems we're both not convinced that this is a desirable functionality
to have in OONI mobile v2.0, because, basically, the app is really
not designed to work like this.
The most compelling argument that @lorenzoPrimi brought, in my
opinion, is how to correctly estimate the elapsed time in light
of the fact that more URLs are tested.
While I can see many hackish ways to implement this, I also believe
it's not the job of MK to perform this sort of magic without the apps
knowing it. I'd rather implement in MK a function that takes a list
of URL in input and emits a normalised/expanded list in output.
This is the reason why I'm removing the existing code, rather than
just disabling it. We should discuss more and come out with a …
=> web_connectivity: revert testing also http with https URL

src/libmeasurement_kit/nettests/runnable.cpp, src/libmeasurement_kit/nettests/runnable.hpp, src/libmeasurement_kit/nettests/web_connectivity.cpp
Today, I discussed this issue further with @lorenzoPrimi and it
seems we're both not convinced that this is a desirable functionality
to have in OONI mobile v2.0, because, basically, the app is really
not designed to work like this.
The most compelling argument that @lorenzoPrimi brought, in my
opinion, is how to correctly estimate the elapsed time in light
of the fact that more URLs are tested.
While I can see many hackish ways to implement this, I also believe
it's not the job of MK to perform this sort of magic without the apps
knowing it. I'd rather implement in MK a function that takes a list
of URL in input and emits a normalised/expanded list in output.
This is the reason why I'm removing the existing code, rather than
just disabling it. We should discuss more and come out with a …
=> web_connectivity: revert testing also http with https URL [stable]

src/libmeasurement_kit/ooni/templates.cpp
This appears to be the main culprit of #1739. However, TBH, this
is not a complete fix, because the proper fix would be to (1) make
sure we don't have default arguments anywhere and (2) make sure
we don't have singletons anywhere and (3) understand what was the
condition under which a singleton was moved and where.
However, this is a good first step. My plan, in going forward,
is to apply this diff also to stable, tag v0.9.3, and then
work on (1), (2), and (3) inside the master branch.
=> fix(s/l/o/templates.cpp): pass proper logger to dns::query

Doxyfile, configure.ac, include/measurement_kit/common/version.h, include/measurement_kit/common/version.h.in, script/update-includes, src/libmeasurement_kit/ooni/templates.cpp, src/measurement_kit/main.cpp
[This backports f1ff62786f8e80b869ebad3fee5e1235b9654b7d from the master branch to stable. Original log follows:]
> This appears to be the main culprit of #1739. However, TBH, this
> is not a complete fix, because the proper fix would be to (1) make
> sure we don't have default arguments anywhere and (2) make sure
> we don't have singletons anywhere and (3) understand what was the
> condition under which a singleton was moved and where.
>
> However, this is a good first step. My plan, in going forward,
> is to apply this diff also to stable, tag v0.9.3, and then
> work on (1), (2), and (3) inside the master branch.
Also, this exposes the `--ca-bundle-path` flag (see #1737)
=> Release v0.9.3

src/libmeasurement_kit/nettests/runnable.cpp
Closes #1758.
I played a bit with DASH settings without being able to cause
the test to produce a failure-less result.
It does not matter much. This diff makes the code more robust
anyway, because we'll make sure we have a failure.
Also, in the original bug report, that was the case. So, it
seems we should christen MK v0.9.5.
=> runnable: make sure we always have a failure key

Doxyfile, configure.ac, include/measurement_kit/common/version.h, include/measurement_kit/common/version.h.in, script/update-includes
It was pointed out that it's perhaps better that the latest
relase is stable. In all regards, this is v0.9.4 because
of the issue explained in #1761. So, people should actually
use v0.9.4, but this v0.9.6 tag exists such that we have a
stable release as the tip of the stable branch.
Suggested by @evfirerob.
Individual commits:
- release 0.9.6: step 1: update version number
- release 0.9.6: step 2: update headers
Using a PR with a merge commit to clearly mark this is as
a point in the stable history when something happens.
=> Tag v0.9.6 to have a working stable release

src/libmeasurement_kit/nettests/runnable.cpp
This reverts commit 982a9c9a89bda813e1e6e1f1a2488b84c1b270e7.
See #1761
=> Revert "runnable: make sure we always have a failure key"

CONTRIBUTING.md, README.md
In the interest of making the build process easier, this commit
removes the stable branch and only keeps the master branch.
If there's need to make an emergency stable release, then I will
create temporary branches. The workflow in which I also need to
maintain a stable branch has too much toil and too little advantages
known to me. I can easily use tags instead.
=> [ci skip] stop mentioning the stable branch everywhere

README.md, include/measurement_kit/README.md
1. change the tagline to avoid referencing C++14
2. mention the Go engine
3. clarify that the Android API is android-libs (as it seems
less surprising to continue improving that rather than
restarting from scratch with mkall-java)
4. clarify that we will try to keep the highest level API
backwards compatible (or trivially upgradable), because,
if we ever switch to Go, that's what we'll aim for
Closes #1787
See https://github.com/measurement-kit/mkall-java/issues/8
=> [ci skip] API documentation improvements

src/libmeasurement_kit/ooni/collector_client.hpp
As agreed with @hellais, the sandbox collector is gone.
Closes #1787
=> collector_client: always use production collector

.ci/appveyor/msys2.bat
After trial and error, I figured out that certainly we need to
install readline otherwise that's missing and awk fails.
Close #1796.
=> appveyor: we need readline for the build to work

README.md
Used to be ./ci/common but that now has changed, as reported
by a OONI user on the OONI slack (thanks!)
Closes #1820.
=> [ci skip] README.md: mention .ci/travis

configure.ac, src/libmeasurement_kit/nettests/runnable.cpp, src/libmeasurement_kit/ooni/http_invalid_request_line.cpp
It also includes an unrelated fix to an annoying issue, so I'll preserve history.
Closes #1823.
Depends on https://github.com/ooni/spec/pull/141.
=> HIRL, runnable now more robust to binary data

README.md
We're not going to write this engine in the measurement-kit
namespace, rather it will be in the ooni namespace.
So, do not mention it here. Closes #1851.
=> [ci skip] README.md: don't mention the Go engine

README.md, include/measurement_kit/README.md
While there, also stop mentioning the Go API, which is not an
official and stable product.
Closes #1853
=> README.md: review and make sure it's up to date

include/measurement_kit/README.md
It has been like this since forever, but it wasn't documented.
=> Document WARNING as the default log level

Doxyfile, configure.ac, include/measurement_kit/common/version.h, include/measurement_kit/common/version.h.in, script/update-includes
This changes the version number to v0.10.5. After this is merged, we can tag.
=> Release v0.10.5

Doxyfile, configure.ac, include/measurement_kit/common/version.h, include/measurement_kit/common/version.h.in, include/measurement_kit/internal/engine/task.hpp, script/update-includes, src/libmeasurement_kit/engine/task.hpp, src/libmeasurement_kit/ffi.cpp, test/dns/query.cpp, test/ffi/mk_event_create.cpp
JNI's `NewStringUTF` requires modified UTF-8. That is, actually, incompatible UTF-8. In most cases UTF-8 streams are accepted by JNI. See #1877 for exceptions to this rule.
Address this issues with two changes:
1. export `engine::Task` as a public, internal API, such that we can, as a last resort mechanism, modify OONI code interfacing with MK to completely by pass C strings and C code. From C++ it seems easier to get an array of bytes and a size, and to convert that to a Java `byteArray` that then can be converted to a string using native Java code and an encoding. This approach has been documented, e.g., by [Scott Banachowski](http://banachowski.com/deprogramming/2012/02/working-around-jni-utf-8-strings/).
2. modify the way in which we returns serialised JSONs such that we only use …
=> engine, ffi: emit UTF-7 without U+0000

src/libmeasurement_kit/dns/libevent_query.hpp, src/libmeasurement_kit/ffi.cpp, src/libmeasurement_kit/http/response_parser.cpp, src/libmeasurement_kit/traceroute/android.cpp
These were deprecated in C++14.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> treewide: Change legacy C headers to C++ ones

src/libmeasurement_kit/ooni/bouncer.hpp, src/libmeasurement_kit/ooni/collector_client.hpp, src/libmeasurement_kit/ooni/orchestrate.hpp, test/http/request.cpp, test/nettests/utils.hpp, test/ooni/bouncer.cpp
Attempt to always use ps-test.ooni.io for testing. Make sure we use
the canonical hosts for orchestra, rather than deprecated ones.
Closes #1896
=> Update the OONI servers we use

src/libmeasurement_kit/neubot/dash_impl.hpp
The servers now support it, so why not?
=> dash: use HTTPS by default

m4/mk.m4
Otherwise we segfault as soon as we attempt using OpenSSL.
=> m4/mk.m4: use right OpenSSL on macOS

src/libmeasurement_kit/nettests/whatsapp.cpp, src/libmeasurement_kit/ooni/whatsapp.cpp, test/dns/query.cpp
While there, make sure the `tcp_connect` field of whatsapp ensures that `failure` is a nullable string.
This is part of https://github.com/ooni/probe-engine/issues/341.
=> whatsapp: urgent band aid to disable CIDR logic

OREADME.md, README.md
Part of https://github.com/measurement-kit/measurement-kit/issues/1921. Subject to changes as we further our understanding of how to smooth our transition. Main paint point seems to be iOS, for which we have not done basically any work yet (except we know we can build a framework).
=> Officially deprecate MK and describe upgrade path

configure.ac
Libevent >= 2.1.12 is using if_nametoindex. This function is part of
the iphlpapi library. So we need to link to it.
See also https://github.com/measurement-kit/homebrew-measurement-kit/commit/2d94c2eb4cc26deb46d0b6578efd737932422d70
=> configure.ac: link with iphlpapi required by libevent >= 2.1.12

include/measurement_kit/nettests.hpp, script/autoapi/autoapi, script/autoapi/nettests.hpp.j2, src/libmeasurement_kit/ooni/bouncer.hpp, src/libmeasurement_kit/ooni/collector_client.hpp, src/libmeasurement_kit/ooni/facebook_messenger.cpp, src/libmeasurement_kit/ooni/orchestrate.hpp, test/http/request.cpp, test/mkapi/orchestra.cpp, test/nettests/utils.hpp
As indicated at https://github.com/ooni/sysadmin/pull/452, we wanna use ams-pg.ooni.org as our testing probe service for some time while ps-test.ooni.io is down and while we are working to refactor APIs at ams-pg.ooni.org.
=> all: use ams-pg.ooni.org as testing probe service
